### ISSUE TITLE
Can not create IBC channel or RPC port connection fail.

### ISSUE THREAD

**Issue by Adamtruong6868** [dymensionxyz/roller#1019]
### Roller version

1.6.4-alpha-rc01

### OS

Ubuntu 22.4

### Processor Architecture

10 cores

### Others

60 GB RAM and 1,600 GB SSD

### Steps to reproduce it

roller relayer setup

### Expected result

IBC channel creating completed

### Actual result

![image](https://github.com/user-attachments/assets/75ce7472-e6c9-4e77-8578-620b0eea50b5)

### Log Files

[rollapp.log](https://github.com/user-attachments/files/17088714/rollapp.log)
[relayer.log](https://github.com/user-attachments/files/17088715/relayer.log)

### Notes

I tried with 2 rollapps, it's not stable and randomly error for RPC port (26657) or IBC relay channel creating. 
When update metadata, it's not link to web dashboard.
![image](https://github.com/user-attachments/assets/39b137e1-ebe4-49ca-a10f-10ec1a8cdabb)

**Comment by Adamtruong6868** [comment]
Kepl and metamask wallet can not send tokens in playground

**Comment by artemijspavlovs** [comment]
was addressed in the latest `roller` release `v1.7.3-alpha*`.
