### ISSUE TITLE
Have a problem start rollap

### ISSUE THREAD

**Issue by aksamlan** [dymensionxyz/roller#1029]
### Roller version

1.6.4-alpha-rc03

### OS

linux

### Processor Architecture

amd

### Others

when I start the rollap I get the error as in the following picture 
![image](https://github.com/user-attachments/assets/689f61e4-a7cd-49c3-b3aa-0523875d37b2)

### Steps to reproduce it

start rollap

### Expected result

rollap needs to start

### Actual result

error

### Log Files

[light_client.log](https://github.com/user-attachments/files/17090395/light_client.log)
[rollapp.log](https://github.com/user-attachments/files/17090396/rollapp.log)

**Comment by artemijspavlovs** [comment]
hi @aksamlan , would you mind sharing the genesis file of the RollApp?
