### ISSUE TITLE
Relayer stuck at starting due to error: genesis supply is incorrect/invalid character "/n" in the genesis file.

### ISSUE THREAD

**Issue by Proskhmer08** [dymensionxyz/roller#1032]
### Roller version

1.6.4-alpha-rc01

### OS

Linux Ubuntu 22.04

### Processor Architecture

GNU/Linux 5.15.0-122-generic x86_64

### Others

Dedicated 62GM RAM, 1TB disk

### Steps to reproduce it

The steps to reproduce it is in the Dymension doc for RollApp creation for 3D Playground. I followed it step by step. After starting the RollApp, next step was to start the relayer, but the relayer remained in, "starting..." due to issue with the sequencer not starting. Logs kept showing the panic due to genesis supply is incorrect. But there was also part of the RollApp log that shows something about invalid character "/n" in the genesis file which was never tampered with manually. 

### Expected result

RollApp should be healthy and relayer starting well. I verified the genesis file, and it showed two accounts that should add up to the error in the rollapp status error msg. 

### Actual result

Relayer stuck at starting while RollApp sequencer stopped running. 
The rollapp log shows a panic: genesis supply is incorrect. expected 9000000000000ages, 10000000000000ages, got 10000000000000ages. 

### Log Files

<img width="1078" alt="Screenshot 2024-09-23 at 10 47 12 AM" src="https://github.com/user-attachments/assets/dfdf60a6-e29a-408e-9be9-8e072c12a8a3">
<img width="911" alt="Screenshot 2024-09-23 at 10 46 53 AM" src="https://github.com/user-attachments/assets/b7d09082-5864-41a6-bcdb-fac65476f248">
<img width="1078" alt="Screenshot 2024-09-23 at 10 46 29 AM" src="https://github.com/user-attachments/assets/aa5a9210-1845-440e-9f86-fb02ea9cf40e">
<img width="1078" alt="Screenshot 2024-09-23 at 10 46 22 AM" src="https://github.com/user-attachments/assets/4d8f6123-e369-400d-9516-37b433254c3d">
<img width="1078" alt="Screenshot 2024-09-23 at 10 46 09 AM" src="https://github.com/user-attachments/assets/213b8772-d7f1-4d87-ae6c-72af407f01c1">
<img width="1073" alt="Screenshot 2024-09-23 at 11 32 16 AM" src="https://github.com/user-attachments/assets/63b9d8c0-a881-425d-83a3-fafd11a45d32">

**Comment by artemijspavlovs** [comment]
the supply issue is related to the genesis file generated on the https://playground.dymension.xyz.

can you try to update the tokenomics step and regenerate the genesis file by clicking the `update` button, then try running the rollapp again.

**Comment by Proskhmer08** [comment]
> the supply issue is related to the genesis file generated on the https://playground.dymension.xyz.
> 
> can you try to update the tokenomics step and regenerate the genesis file by clicking the `update` button, then try running the rollapp again.

Hi. I tried multiple times previously. It gave me the signature verification failed and it still does. I do have enough dym for gas.


<img width="1244" alt="Screenshot 2024-09-24 at 10 55 16 PM" src="https://github.com/user-attachments/assets/344127f5-e55c-4e94-b0cc-7bb9d0aac291">

**Comment by artemijspavlovs** [comment]
was addressed in the latest `roller` release `v1.7.3-alpha*`.
