### ISSUE TITLE
roller relayer setup

### ISSUE THREAD

**Issue by barburan1** [dymensionxyz/roller#1033]
### Roller version

1.6.4-alpha-rc03

### OS

Ubuntu 20.04.6 LTS

### Processor Architecture

x86_64

### Others

6 gpu 16 ram

### Steps to reproduce it

![Ekran görüntüsü 2024-09-23 194117](https://github.com/user-attachments/assets/1ddc0eb3-83e8-4fb9-aff9-b40ba81f4566)
When I enter the roller relayer setup command, it says **"ERROR   failed to get current block height: command execution failed: exit status 1, stderr: Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32000 - load hash from index: load block hash for height 0: not found".**

### Expected result

roller to be created

### Actual result

SUCCESS  RollApp is healthy
  ERROR   failed to get current block height: command execution failed: exit status 1, stderr: Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32000 - load hash from index: load block hash for height 0: not found
          Usage:
            rollapp-evm query block [height] [flags]

          Flags:
            -h, --help          help for block
            -n, --node string   Node to connect to (default "tcp://localhost:26657")

          Global Flags:
                --chain-id string     The network chain ID
                --home string         directory for config and data (default "/root/.rollapp_evm")
                --log_format string   The logging format (json|plain) (default "plain")
                --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
                --trace               print out full stack trace on errors
 INFO  checking dymint block time settings (want: 5s)
 INFO  block time is higher then recommended when creating ibc channels:  1h0m0s
 INFO  updating dymint config
 INFO  block time:  5s
 INFO  reverting dymint config to 1h
 INFO  checking dymint block time settings (want: 1h0m0s)
 INFO  updating dymint config
 INFO  block time:  1h0m0s

### Log Files

ERROR   failed to get current block height: command execution failed: exit status 1, stderr: Error: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32000 - load hash from index: load block hash for height 0: not found

**Comment by artemijspavlovs** [comment]
please install the latest rc - `rc06` and try running the relayer setup again, if the problem persists - please attach the  `~/.roller/rollapp/rollapp.log` and `~/.roller/relayer/relayer.log` log files

**Comment by BaidocVlad** [comment]
We have the same issue. The sequencer it's healthy but I have some strange logs in `~/.roller/rollapp/rollapp.log`


`time="Sep 24 08:59:08.300" level=info msg="port binded[port transfer]" module=x/ibc/port
time="Sep 24 08:59:08.300" level=info msg="claimed capability[module transfer name ports/transfer capability 1]" module=x/capability
time="Sep 24 08:59:08.300" level=debug msg="running initialization for module[module feegrant]"
time="Sep 24 08:59:08.300" level=debug msg="running initialization for module[module hubgenesis]"
time="Sep 24 08:59:08.300" level=debug msg="running initialization for module[module hubs]"
time="Sep 24 08:59:08.300" level=debug msg="running initialization for module[module rollappparams]"
time="Sep 24 08:59:08.313" level=info msg="starting block manager[proposer true]" module=block_manager
time="Sep 24 08:59:09.411" level=error msg="Failed to sync Celestia DA[attempt 1 error RPC client error: sendRequest failed: request failed, http status 415 Unsupported Media Type]" module=celestia
time="Sep 24 08:59:19.595" level=error msg="Failed to sync Celestia DA[attempt 2 error RPC client error: sendRequest failed: request failed, http status 415 Unsupported Media Type]" module=celestia
time="Sep 24 08:59:29.779" level=error msg="Failed to sync Celestia DA[attempt 3 error RPC client error: sendRequest failed: request failed, http status 415 Unsupported Media Type]" module=celestia`

**Comment by artemijspavlovs** [comment]
@BaidocVlad thanks for sharing this, it failing to sync Celestia might be related to unhealthy celestia node, can you try to change the `DA.state_node` value in `~/.roller/roller.toml` file and restarting the rollapp services please?

you should use state nodes for [Mocha network](https://docs.celestia.org/nodes/mocha-testnet#community-data-availability-da-grpc-endpoints-for-state-access), for example:

```
mocha-4-consensus.mesa.newmetric.xyz
```

**Comment by barburan1** [comment]
> Lütfen en son rc'yi yükleyin `rc06`ve röle kurulumunu tekrar çalıştırmayı deneyin, sorun devam ederse lütfen `~/.roller/rollapp/rollapp.log`ve `~/.roller/relayer/relayer.log`günlük dosyalarını ekleyin

![2024-09-24_11-23-21](https://github.com/user-attachments/assets/b70c5e24-6498-4e3b-beb4-d053b6161077)

**Comment by BaidocVlad** [comment]
> @BaidocVlad thanks for sharing this, it failing to sync Celestia might be related to unhealthy celestia node, can you try to change the `DA.state_node` value in `~/.roller/roller.toml` file and restarting the rollapp services please?
> 
> you should use state nodes for [Mocha network](https://docs.celestia.org/nodes/mocha-testnet#community-data-availability-da-grpc-endpoints-for-state-access), for example:
> 
> ```
> mocha-4-consensus.mesa.newmetric.xyz
> ```

I change it but I still get :

`time="Sep 24 11:17:50.034" level=error msg="Failed to sync Celestia DA[attempt 1 error RPC client error: sendRequest failed: request failed, http status 415 Unsupported Media Type]" module=celestia`

**Comment by artemijspavlovs** [comment]
was addressed in the latest `roller` release `v1.7.3-alpha*`.
