### ISSUE TITLE
failed to create IBC Channel when setup relayer

### ISSUE THREAD

**Issue by ardianreiss** [dymensionxyz/roller#1040]
### Roller version

1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

WASM

### OS

Linux

### Processor Architecture

x86_64

### Steps to reproduce it

![Untitled](https://github.com/user-attachments/assets/3d0cba63-5073-40b5-8f09-34abf930eeae)
when i want to set up relayer, always `failed to create IBC channel: command execution failed: exit status 1`

### Expected result

relayer will be started

### Actual result

root@vmi2039051:~# roller relayer setup
 SUCCESS  RollApp is healthy
 SUCCESS  rollapp has reached the necessary height
Directory /root/.roller/relayer is not empty. Do you want to overwrite it? [y/N]: No
 INFO  ensuring relayer keys are present
 INFO  checking relayer-hub-key
 INFO  checking relayer-rollapp-key
 INFO  ensuring relayer keys are present
 INFO  checking relayer-rollapp-key
 INFO  checking relayer-hub-key
 SUCCESS  RollApp is healthy
no channel found. would you like to create a new IBC channel for bishachain_10492-1? [y/N]: Yes
 INFO  establishing IBC transfer channel
 INFO  💈 Creating connection...
  ERROR   failed to create IBC channel: command execution failed: exit status 1
 INFO  reverting dymint config to 1h
 INFO  checking dymint block time settings (want: 1h0m0s)
 INFO  updating dymint config
 INFO  block time:  1h0m0s

### Log Files

root@vmi2039051:~# tail ~/.roller/relayer/relayer.log
2024/09/25 07:00:48 can't find active connection in the configuration file
Error: path with name hub-rollapp does not exist
2024/09/25 07:04:24 no active rollapp connection id found in the configuration file
2024/09/25 07:04:24 no active hub connection id found in the configuration file
2024/09/25 07:04:24 can't find active connection in the configuration file
2024/09/25 07:04:24 no active connection found
2024/09/25 07:04:37 no active rollapp connection id found in the configuration file
2024/09/25 07:04:37 no active hub connection id found in the configuration file
2024/09/25 07:04:37 can't find active connection in the configuration file
Error: path with name hub-rollapp does not exist

**Comment by artemijspavlovs** [comment]
was addressed in the latest `roller` release `v1.7.3-alpha*`
