### ISSUE TITLE
Can't update sequencer metadata

### ISSUE THREAD

**Issue by blacktokyo96** [dymensionxyz/roller#1049]
### Roller version

💈 Roller version 1.6.4-alpha-rc01

### Rollpp type (EVM/WASM) and version

HEAD-a34bc942d86d658a11038c69e860c973e96a1053

### OS

Linux

### Processor Architecture

x86_64

### Others

![Screenshot 2024-09-28 195902](https://github.com/user-attachments/assets/4ae02e5a-c774-4160-96a7-ab68c9e8713c)

### Steps to reproduce it

i can't finalizing transaction for update sequencer metadata

### Expected result

metadata sequencer rpc update

### Actual result

 transaction failed timeout waiting for transaction

### Log Files

time="Sep 22 02:22:56.618" level=info msg="starting node with ABCI dymint in-process[]"
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting multiAppConn service impl multiAppConn]" module=proxy
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting localClient service impl localClient]" connection=query module=abci-client
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting localClient service impl localClient]" connection=snapshot module=abci-client
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting localClient service impl localClient]" connection=mempool module=abci-client
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting localClient service impl localClient]" connection=consensus module=abci-client
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting EventBus service impl EventBus]" module=events
time="Sep 22 02:22:56.619" level=info msg="service start[msg Starting PubSub service impl PubSub]" module=pubsub
time="Sep 22 02:22:56.772" level=info msg="service start[msg Starting IndexerService service impl IndexerService]" module=txindex
time="Sep 22 02:22:56.772" level=info msg="failed to find state in the store, creating new state from genesis[]"
time="Sep 22 02:22:56.772" level=info msg="service start[msg Starting RPC service impl RPC]"
time="Sep 22 02:22:56.774" level=debug msg="limiting number of connections[limit 900]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name genesis]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name genesis_chunked]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name block_results]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name subscribe]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name blockchain]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name broadcast_tx_sync]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name health]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name tx_search]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name unconfirmed_txs]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name num_unconfirmed_txs]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name broadcast_tx_async]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name unsubscribe]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name check_tx]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name dump_consensus_state]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name consensus_params]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name abci_info]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name commit]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name block_search]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name validators]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name consensus_state]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name broadcast_evidence]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name status]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name block_by_hash]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name tx]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name broadcast_tx_commit]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name unsubscribe_all]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name net_info]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name block]"
time="Sep 22 02:22:56.776" level=debug msg="registering method[name abci_query]"
time="Sep 22 02:22:56.776" level=debug msg="CORS enabled[origins [*] methods [HEAD GET POST] headers [Origin Accept Content-Type X-Requested-With X-Server-Time]]"
time="Sep 22 02:22:56.776" level=info msg="service start[msg Starting Node service impl Node]"
time="Sep 22 02:22:56.776" level=info msg="starting P2P client[]"
time="Sep 22 02:22:56.776" level=info msg="serving HTTP[listen address [::]:26657]"
time="Sep 22 02:22:56.806" level=info msg="Listening on:[address /ip4/45.10.161.83/tcp/26656/p2p/12D3KooWFRyVXMbbzq4MJ5DMRT3zvXiaMAzERb2giePrDu6cczyW]" module=p2p
time="Sep 22 02:22:56.806" level=info msg="Listening on:[address /ip4/127.0.0.1/tcp/26656/p2p/12D3KooWFRyVXMbbzq4MJ5DMRT3zvXiaMAzERb2giePrDu6cczyW]" module=p2p
time="Sep 22 02:22:56.806" level=debug msg="Setting up gossiping.[]" module=p2p
time="Sep 22 02:22:56.809" level=debug msg="Setting up DHT.[]" module=p2p
time="Sep 22 02:22:56.809" level=info msg="No bootstrap nodes configured.[]" module=p2p
time="Sep 22 02:22:56.810" level=debug msg="Setting up active peer discovery.[]" module=p2p
time="Sep 22 02:22:56.812" level=debug msg="Setting up block sync protocol[]" module=p2p
time="Sep 22 02:22:56.812" level=info msg="Starting Celestia Data Availability Layer Client.[]" module=celestia

### Notes

N/A

**Comment by artemijspavlovs** [comment]
please update to the latest version of roller and let us know whether the issue persists
