### ISSUE TITLE
Pool Create Bug

### ISSUE THREAD

**Issue by geocmsk** [dymensionxyz/roller#1051]
### Roller version

1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

v2.2.0-rc01-51-gfe4246e

### OS

Ubuntu 24.04.1 LTS

### Processor Architecture

x86_64

### Others

8 CPU + 16GB RAM VPS HETZNER

### Steps to reproduce it

I created a pool today but the pool I created in the playground did not appear, then when I checked my txs, the tx I created the pool appeared to be successful. However, my pool is still not visible and I cannot add liquidity because of this bug. I request that the issue be reviewed and the bug be fixed. There are many testers who encounter this event and cannot add a pool. My rollapp is healthy but I cannot create a pool. Also, although the pool was not created, the market cap of my rollapp was calculated, which I think is a mistake. For your information

REGARDS
CemS

rollapp id: cemsdevelopment_30601-1
DYM wallet: dym1xz9282gv3wkntceqmgu3ug2sv8wahnyls9u9yw
Pool Creation Tx: https://pg.dym.fyi/tx/7D286E2FA44669092D61D1BCDA5E09A0820895608DFFAF32DCCC0E0C5198B656

### Expected result

![image](https://github.com/user-attachments/assets/4aca0461-c87d-4225-9a8e-9e28f4e6d03b)
![image](https://github.com/user-attachments/assets/63226b2f-d16b-4f98-88c6-bbb235f0d850)

### Actual result

![image](https://github.com/user-attachments/assets/d019463e-67e0-4b1f-ab33-69212bc3c027)
![image](https://github.com/user-attachments/assets/654d6295-b09b-4615-8e85-bb625a38e01d)

**Comment by yishay-dym** [comment]
This bug has been resolved, thank you @geocmsk for pointing this out.

**Comment by geocmsk** [comment]
I didn't expect you to respond so quickly, you are really great! Thanks!
