### ISSUE TITLE
Sequencer would not start because Rollap genesis supply differs from  1b

### ISSUE THREAD

**Issue by Jaytechent** [dymensionxyz/roller#1053]
### Roller version

 Roller version 1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

Evm

### OS

Debian

### Processor Architecture

Amd64

### Others

16gb ram 100gb ssd

### Steps to reproduce it

Create a rollapp with a genesis supply of 80b using the portal and go back to the cli , initialize the rollap you created using the CLI this time, and bond the Rollap to you sequencer, there after proceed to run the relayer, your sequencer would stop after bonding , i proceed to load the relayer and got the log below.

### Expected result

  💈 badger 2024/09/29 18:21:47 INFO: All 0 tables opened in 0s
          badger 2024/09/29 18:21:47 INFO: Discard stats nextEmptySlot: 0
          badger 2024/09/29 18:21:47 INFO: Set nextTxnTs to 0
          badger 2024/09/29 18:21:47 INFO: Deleting empty file: /root/.roller/rollapp/data/dymint/000420.vlog
          panic: genesis supply is incorrect, expected 10000000000000000000000000000agmc,70000000000000000000000000000agmc, got 80000000000000000000000000000agmc

          goroutine 66 [running]:
          github.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.InitGenesis({{{{0x4174f00, 0xc000a25d10}, {0x41305c8, 0xc0015365c0}, {0x4178460, 0xc001b294a0}}, {0x4174f00, 0xc000a25d10}, {0x4178460, 0xc001b294a0}, ...}, ...}, ...)
                /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/bank/keeper/genesis.go:29 +0x585
          github.com/cosmos/cosmos-sdk/x/bank.AppModule.InitGenesis({{{_, _}}, {_, _}, {_, _}}, {{0x4156230, 0x60ab460}, {0x4174e20, 0xc0008344c0}, ...}, ...)
                /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/x/bank/module.go:149 +0x183
          github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x4156230, 0x60ab460}, {0x4174e20, 0xc0008344c0}, {{0x0, 0x0}, {0xc001db3a58, 0x12}, 0x0, ...}, ...}, ...)
                /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/types/module/module.go:322 +0x33f
          github.com/dymensionxyz/rollapp-evm/app.(*App).InitChainer(_, {{0x4156230, 0x60ab460}, {0x4174e20, 0xc0008344c0}, {{0x0, 0x0}, {0xc001db3a58, 0x12}, 0x0, ...}, ...}, ...)
                /tmp/rollapp4035620117/app/app.go:876 +0x285
          github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001b3f880, {{0x18701a80, 0xede8b461b, 0x0}, {0xc001db3a58, 0x12}, 0xc000848420, {0xc0018de600, 0x1, 0x1}, ...})
                /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.16/baseapp/abci.go:71 +0x3f5
          github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0008dff20, {{0x18701a80, 0xede8b461b, 0x0}, {0xc001db3a58, 0x12}, 0xc000848420, {0xc0018de600, 0x1, 0x1}, ...})
                /root/go/pkg/mod/github.com/dymensionxyz/cometbft@v0.34.29-0.20240906143736-1e3959c2826e/abci/client/local_client.go:272 +0xf8
          github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0?, {{0x18701a80, 0xede8b461b, 0x0}, {0xc001db3a58, 0x12}, 0xc000848420, {0xc0018de600, 0x1, 0x1}, ...})
                /root/go/pkg/mod/github.com/dymensionxyz/cometbft@v0.34.29-0.20240906143736-1e3959c2826e/proxy/app_conn.go:77 +0x55
          github.com/dymensionxyz/dymint/block.(*Executor).InitChain(0xc000a009a0, 0xc000742b00, {0xc00157adc8, 0x1, 0xc00157add0?})
                /root/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240916140329-d51b961e7e0d/block/executor.go:69 +0x41f
          github.com/dymensionxyz/dymint/block.(*Manager).RunInitChain(0xc000790540, {0x338a826?, 0x47351d?})
                /root/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240916140329-d51b961e7e0d/block/initchain.go:20 +0x92
          github.com/dymensionxyz/dymint/block.(*Manager).Start(0xc000790540, {0x4156a10, 0xc001926870})
                /root/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240916140329-d51b961e7e0d/block/manager.go:146 +0xcb
          github.com/dymensionxyz/dymint/node.(*Node).OnStart(0xc000745808)
                /root/go/pkg/mod/github.com/dymensionxyz/dymint@v1.2.0-rc01.0.20240916140329-d51b961e7e0d/node/node.go:234 +0x1fe
          github.com/tendermint/tendermint/libs/service.(*BaseService).Start(0xc000745808)
                /root/go/pkg/mod/github.com/dymensionxyz/cometbft@v0.34.29-0.20240906143736-1e3959c2826e/libs/service/service.go:144 +0x2f5
          github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.startInProcess(_, {{0x0, 0x0, 0x0}, {0x4191ed0, 0xc000a1ec30}, 0x0, {0xc001a3be30, 0x12}, {0x417fe00, ...}, ...}, ...)
                /tmp/rollapp4035620117/cmd/rollappd/cmd/start.go:335 +0xa78
          github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.StartCmd.func2.1()
                /tmp/rollapp4035620117/cmd/rollappd/cmd/start.go:176 +0x5b
          github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.wrapCPUProfile.func2()
                /tmp/rollapp4035620117/cmd/rollappd/cmd/start.go:663 +0x23
          created by github.com/dymensionxyz/rollapp-evm/cmd/rollappd/cmd.wrapCPUProfile in goroutine 1
                /tmp/rollapp4035620117/cmd/rollappd/cmd/start.go:662 +0x23f

### Actual result

It should load my relayer.

### Log Files

![image](https://github.com/user-attachments/assets/75c15e80-70d5-4b21-8d42-9fedb663d80c)

### Notes

Get back to me once solved, i would like o bring the rollapp back to live

**Comment by artemijspavlovs** [comment]
old, closing. there was a genesis generation but at the time of issue creation
