### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by omerbek** [dymensionxyz/roller#1055]
### Implementation ideas

I can access the platform with the wallet I staked Dym on the main network. However, when I am not using the platform, I get an error when I try to send via the wallet application (Keplr, Metamask).

The platform provides a transfer to the dym address. When we try to send via Keplr, we get an error. Similarly, even though I changed the rpc in metamask, we get an error as in the video.

Our Telegram bot provides sending within Rollapp networks. We want to make a Rollapp token faucet so that people can access it more easily within the Dym network. However, Dym sending is not provided on the evm side.

https://github.com/user-attachments/assets/11617ac4-ccf8-4ed2-abc3-03ffa57a081a

**Comment by omritoptix** [comment]
thanks for your report @omerbek. should be fixed now.

**Comment by artemijspavlovs** [comment]
should be fixed, closing, please reopen and tag us if the issue persists
