### ISSUE TITLE
Unable to create an IBC channel. Result command execution failed:exit status 1

### ISSUE THREAD

**Issue by Proskhmer08** [dymensionxyz/roller#1056]
### Roller version

1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

EVM-v2.2.0-rc01-51-gfe4246e

### OS

Linux

### Processor Architecture

GNU/Linux 5.15.0-122-generic x86_64

### Others

System load:             0.06
  Usage of /:              3.1% of 879.51GB
  Memory usage:            3%
  Swap usage:              0%
  Processes:               236

### Steps to reproduce it

`Rollapp` is healthy. Status shows `rollapp` and `da-light-client` are active. 

When executing, `roller relayer setup`, without overwriting the current relayer, and trying to create a new IBC channel, the process resulted in:

```
 INFO  establishing IBC transfer channel
 INFO  💈 Creating connection...
  **ERROR   failed to create IBC channel: command execution failed: exit status 1**
 INFO  reverting dymint config to 1h
 INFO  checking dymint block time settings (want: 1h0m0s)
 INFO  updating dymint config
 INFO  block time:  1h0m0s
```

I have tried multiple attempts and all resulted in the same error. Please reference the attached screenshots.

The screenshots below shows the troubleshooting steps that I took including checking firewall, and checking the logs for `RollApp`, `da-light-client` and `relayer`.

<img width="1431" alt="Screenshot 2024-09-29 at 7 53 05 PM" src="https://github.com/user-attachments/assets/2b79c8fc-fefc-46f7-ac8d-8cd86445f381">

Here is the log for the `Rollapp`. The previous `RollApp` that I attempted to run, showed a `panic` msg with the `genesis supply incorrect` msg. But here, there's `no issue with the genesis supply`. 

<img width="982" alt="Screenshot 2024-09-29 at 7 53 45 PM" src="https://github.com/user-attachments/assets/7e273b19-378c-4c79-9cfd-8b98470f1700">

Here is the `da-light-client` log, which mostly shows no peer.
<img width="982" alt="Screenshot 2024-09-29 at 7 54 21 PM" src="https://github.com/user-attachments/assets/9ffe0d77-615f-498c-be3f-06e967926da7">

I checked `systemctl status` on `rollapp`, `da-light-client` and `roller relayer status`:
<img width="982" alt="Screenshot 2024-09-29 at 7 55 10 PM" src="https://github.com/user-attachments/assets/cbbdae47-db41-4794-a361-32f952ab4ed5">

Here is the version for `Go`, `Docker`, and `Roller version`. `Rollappd version` is in the text above.
<img width="438" alt="Screenshot 2024-09-29 at 7 57 40 PM" src="https://github.com/user-attachments/assets/69658273-6ad1-4865-86fc-5694ff6112c2">

And here are the errors from the `relayer` log:
<img width="978" alt="Screenshot 2024-09-29 at 8 07 53 PM" src="https://github.com/user-attachments/assets/390bdd91-b818-42d1-a881-abc05ba3ef14">

And also below is the latest log for the `relayer`:

<img width="978" alt="Screenshot 2024-09-29 at 8 08 42 PM" src="https://github.com/user-attachments/assets/c41b840d-cfce-4136-8856-2987f061a3b3">

Firewall is also configured for port `26657` for incoming and outgoing on the server page as well.

<img width="758" alt="Screenshot 2024-09-29 at 8 17 45 PM" src="https://github.com/user-attachments/assets/586cbf79-13a5-4e8f-b7cf-c29ac876e25e">

### Expected result

The expected result should've been a smooth process with a successful creation of the IBC channel which would allow me to move on to creating eIBC client and doing transfers. 

### Actual result

The actual result is the same persisted error code.

 `ERROR   failed to create IBC channel: command execution failed: exit status 1`

### Log Files

Looking at the `relayer log`, I am unable to determine what cause the handshake to terminate.

<img width="982" alt="Screenshot 2024-09-29 at 8 23 32 PM" src="https://github.com/user-attachments/assets/37fd5b5e-042b-4a33-b531-74bde00c3f5d">

There is one erro msg:

`Error: querying connections: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). Failed to read response body: context canceled`

Here's what the client.toml in the Rollapp dir has:

<img width="982" alt="Screenshot 2024-09-29 at 8 26 03 PM" src="https://github.com/user-attachments/assets/f570d01f-8f38-4142-8d5d-17bb54dfcfad">

Here's what the be-json-rpc.toml in the Rollapp dir has:
<img width="982" alt="Screenshot 2024-09-29 at 8 26 30 PM" src="https://github.com/user-attachments/assets/3a290f9c-105e-4d28-92f6-e046b3fb7437">

### Notes

I am thus far, unable to successfully create IBC channel to allow IBC transfers. I am also unable to determine the root cause of the persisting problem here. 

Other troubleshooting steps I took was:

`sudo ufw reload`, `sudo ufw disable`, `sudo ufw enable` and `sudo ufw allow 26657`.

**Comment by Proskhmer08** [comment]
Here is the `Roller Rollapp Status`:


<img width="639" alt="Screenshot 2024-09-29 at 8 50 18 PM" src="https://github.com/user-attachments/assets/4db46e27-1bd1-43ad-b9d9-f3a8bf2260d4">

**Comment by Proskhmer08** [comment]
From the `relayer` log:
```
2024-09-29T18:05:49.776794Z     info    Chain not in sync.      {"chain_id": "dymagestwo_2952-1", "latest_queried_block": 2383, "latest_height": 2403}
2024-09-29T18:05:49.854793Z     info    Connection handshake termination candidate.     {"path_name": "hub-rollapp", "chain_id": "dymagestwo_2952-1", "client_id": "07-tendermint-0", "termination_client_id": "07-tendermint-0", "observed_client_id": "07-tendermint-0", "termination_counterparty_client_id": "07-tendermint-232", "observed_counterparty_client_id": "07-tendermint-232"}
2024-09-29T18:05:49.854822Z     info    Found termination condition for connection handshake.   {"path_name": "hub-rollapp", "chain_id": "dymagestwo_2952-1", "client_id": "07-tendermint-0"}
Error: querying connections: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). Failed to read response body: context canceled
```

**Comment by artemijspavlovs** [comment]
hi, 

this is an occasional issue that happens when a previous IBC channel creation didn't succeed and a new configuration was initialized.

we're currently working on resolving this issue, the next roller version will have a way to seamlessly overcome the IBC related issues. I will update you once there's a commit with a solution for you to test

**Comment by Proskhmer08** [comment]
> hi,
> 
> this is an occasional issue that happens when a previous IBC channel creation didn't succeed and a new configuration was initialized.
> 
> we're currently working on resolving this issue, the next roller version will have a way to seamlessly overcome the IBC related issues. I will update you once there's a commit with a solution for you to test

Thank you. Looking forward to the next release.

**Comment by artemijspavlovs** [comment]
old, closing - latest release (v1.7.3*) have addressed all of the known issues
