### ISSUE TITLE
install.sh has error

### ISSUE THREAD

**Issue by Adamtruong6868** [dymensionxyz/roller#1057]
### Roller version

1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

EVM

### OS

Linux

### Processor Architecture

10 cores

### Steps to reproduce it

<img width="761" alt="image" src="https://github.com/user-attachments/assets/1a55b9e5-7c6a-4872-9fcf-018d6b9345a7">

### Expected result

https://github.com/dymensionxyz/roller/releases/download/v1.6.4-alpha-rc08/roller_Linux_amd64.tar.gz   --progress-bar | sudo tar -xz -C "/tmp/roller_tmp"

### Actual result

<img width="770" alt="image" src="https://github.com/user-attachments/assets/01cc2247-868b-4495-b926-6f3ec9178211">

**Comment by artemijspavlovs** [comment]
we had some build related issues that could've caused this, could you try running the `install.sh` again and lmk whether the issue still persists?
