### ISSUE TITLE
Impossible to create IBC Channel

### ISSUE THREAD

**Issue by AviaOne** [dymensionxyz/roller#1060]
### Roller version

aviaone_11000-1

### Rollpp type (EVM/WASM) and version

WASM

### OS

Ubuntu 22.04.4 LTS

### Processor Architecture

x86_64

### Steps to reproduce it

To reproduce the bug, just need to use this command ->
roller relayer setup

### Expected result

Create relayer !
that's impossible to create a new IBC channel for aviaone_11000-1, for this reason the relayer doesn't start....

### Actual result

![screenshot 2024-10-04 (1)](https://github.com/user-attachments/assets/32f2eeb3-b471-485f-8713-6d0a5d51e92d)
Please see all details in my screenshot
+
Please see the relayer wallet to be sure it's funnded + One IBC client created but not used !!!
https://pg.dym.fyi/address/dym1xqtw074gwsdvmpdgja59mv3255t0g260e269pr

### Log Files

[relayer.log](https://github.com/user-attachments/files/17252166/relayer.log)

### Notes

My rollapp (aviaone_11000-1) have the status "Pre-connection" and just waiting a solution with this issue to be online.
Thanks

**Comment by artemijspavlovs** [comment]
please make sure you're running the latest roller version and try running the setup command again. Also, if the relayer was already initialized, don't override the existing configuration. 

let me know whether the issue persists, thx

**Comment by artemijspavlovs** [comment]
old, closing - ibc creation stability was drastically improved in latest `roller` release ( `v1.7.3-alpha*` )

**Comment by AviaOne** [comment]
Do you mean everything is solved on your side even if if's still not working ?
