### ISSUE TITLE
Rollapp not reaching height 1

### ISSUE THREAD

**Issue by bluebleublack** [dymensionxyz/roller#1062]
### Roller version

💈 Roller version 1.6.4-alpha-release 💈 Build time: 2024-10-02T09:44:53Z 💈 Git commit: 27c8337b291f5bf6a535aa61045c194e271d6c58

### Rollpp type (EVM/WASM) and version

v2.2.0-rc01-51-gfe4246e

### OS

Ubuntu 22.02

### Processor Architecture

x86_64

### Others

It's on Contabo

### Steps to reproduce it

Followed all steps in FAQ to this point https://docs.dymension.xyz/run/operate/relayer
Used my own nginx server with my own domain names and port redirections
Confirmed I can see my server on the subdomains - to the RPC subdomain specifically, can call /status and a response is gotten: {"jsonrpc":"2.0","error":{"code":-32603,"message":"","data":"find latest block: load hash from index: load block hash for height 0: not found"},"id":-1}

### Expected result

For Rollapp to be running blockchain from block 1 onwards

### Actual result

 roller relayer setup
 SUCCESS  RollApp is healthy
  ERROR   rollapp did not reach valid height: timeout waiting for rollapp height to reach 1
 INFO  reverting dymint config to 1h
 INFO  checking dymint block time settings (want: 1h0m0s)
 INFO  updating dymint config
 INFO  block time:  1h0m0s
▀  waiting for rollapp height to be reach 1 (20s)

Chain not working

### Notes

I need to know how I can get my sequencer and relayer and roller working please. I've done this before with DYM and don't understand why this is not working again.

**Comment by bluebleublack** [comment]
Also when I ping the rest api I get this:
{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}

Am at a loss, hoping to run this like I did for DYM rollape before. Please help :)

**Comment by artemijspavlovs** [comment]
@bluebleublack would you mind sharing the `~/.roller/rollapp/rollapp.log` and `~/.roller/da-light-node/light_client.log` files and the output of `roller rollapp status`, it seems that there's something wrong with the rollapp itself
