### ISSUE TITLE
Resolving Proposer Not Found and Sequencer Jailed Issues in Dymension Network

### ISSUE THREAD

**Issue by batuhankocyigit** [dymensionxyz/roller#1066]
### Roller version

1.6.4-alpha-rc08

### Rollpp type (EVM/WASM) and version

EVM

### OS

ubuntu 22.04

### Processor Architecture

AMD EPYC

### Others

Processor (CPU): AMD Ryzen 5 3600 12 threads, 4.2 GHz
RAM: 64 GB DDR4
Storage: 1 TB NVMe SSDs
Traffic: Unlimited traffic with 1 Gbit/s

### Steps to reproduce it

I tried creating a new RPC address and updating the metadata again. I sent a large amount of DYM tokens to my sequencer account and tried again. I restarted my rollup, EIBC, and sequencer services.

### Expected result

I expect my metadata services to be successfully updated, and for the current RPC to be replaced with the new one, allowing the system to function properly.

### Actual result

However, when I check the logs:

Proposer not found: This error indicates that a proposer (i.e., the node or individual proposing a block) could not be found when attempting to submit a specific block or transaction. In the Dymension network, each block requires a proposer. If the proposer node is not found, the transaction fails.

Gas wanted: '18446744073709551615': This number represents the maximum uint64 value, indicating that an extremely high gas fee was requested for the transaction. This is likely due to incorrect calculation or an invalid value being passed, resulting in such a large gas limit request.

Gas used: '2139796': This shows the amount of gas consumed during the transaction. While the actual gas usage seems normal, the gas limit requested is significantly higher than it should be.

When I check with the tx hash on the explorer, I get the following output:

Failed to execute message; message index: 0: sequencer is jailed.

![Ekran görüntüsü 2024-10-09 211301](https://github.com/user-attachments/assets/3341fee9-9066-4f43-89d9-f6e07e54147a)
![sequencer jailed](https://github.com/user-attachments/assets/9d1ab8d8-3c98-496d-b0c1-fa22b011610a)

### Log Files

time="Oct  9 18:12:00.903" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:12:11.069" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:12:17.023" level=debug msg="ABCIQuery[path /cosmos.bank.v1beta1.Query/AllBalances height 47062]" module=events
time="Oct  9 18:12:21.226" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:12:31.412" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:12:41.575" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:12:50.902" level=debug msg="WebSocket connection closed[reason websocket: close 1006 (abnormal closure): unexpected EOF]"
time="Oct  9 18:12:51.738" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:13:01.939" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client
time="Oct  9 18:13:02.067" level=debug msg="WebSocket connection closed[reason websocket: close 1006 (abnormal closure): unexpected EOF]"
time="Oct  9 18:13:12.121" level=error msg="Submit batch[startHeight 43682 endHeight 44049 error broadcast tx: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: proposer: not found [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:29] With gas wanted: '18446744073709551615' and gas used: '2139796' : unknown request]" module=settlement_client

### Notes

There are no problems with the statuses of the rollapp, EIBC, and sequencer services, the current version being used is 1.6.4-alpha-rc081.

**Comment by artemijspavlovs** [comment]
jailing was addressed and improved in phase 2 of the playground
