### ISSUE TITLE
Relayer can not handle TXs amount

### ISSUE THREAD

**Issue by Adamtruong6868** [dymensionxyz/roller#1071]
### Roller version

1.6.4-alpha-release

### Rollpp type (EVM/WASM) and version

EVM

### OS

Ubuntu 22.4

### Processor Architecture

AMD 8 cores

### Steps to reproduce it

roller relayer start

### Expected result

Relayer running

### Actual result

<img width="959" alt="image" src="https://github.com/user-attachments/assets/8849b6da-f060-4b9d-bbf5-9d58845a1aa5">

### Log Files

[relayer logs.txt](https://github.com/user-attachments/files/17350279/relayer.logs.txt)

### Notes

i just try to test rollapp with amout if TXs about 1min-2min/TX and the relayer got error.

**Comment by artemijspavlovs** [comment]
already in use, debug port is used by another process.
