### ISSUE TITLE
RollApp tokens are not transferred from RollApp to Dymension: remain in Pending

### ISSUE THREAD

**Issue by seda33** [dymensionxyz/roller#1074]
### Roller version

💈 Roller version 1.6.4-alpha-release 💈 Build time: 2024-10-02T09:44:53Z 💈 Git commit: 27c8337b291f5bf6a535aa61045c194e271d6c58

### Rollpp type (EVM/WASM) and version

EVM

### OS

Ubuntu 22.04.5 LTS"

### Processor Architecture

x86_64

### Others

RollApp tokens are not transferred from RollApp to Dymension: remain in Pending.

### Steps to reproduce it

My Rollapp seems active but I still couldn't transfer my own token CATZE from my own network to the Dymension testnet, my transfer process is still pending. That's why I couldn't create a Pool. That's why I couldn't create a Pool. The server features I use are 8 vCPU - 16 GBRAM - 240 GB Disk local - 0/20 TB Traffic out. I installed eIBC according to what the guide says. But I get errors about EIBC. 

### Expected result

I think you'll need to update eIBC.

### Actual result

also I can transfer Dym test tokens from the Dym TEst network to my own network. you can check here https://pg.dym.fyi/tx/C0289E4906DFAA51C9E2FED16606A4721D49946ACF14FA11EA1A47DB50753538 but if you want to check Dymension Transfer History page it seems still Pending https://playground.dymension.xyz/ibc/status/dymension_2018-1-channel-271-channel-0-1 I 
![Ekran görüntüsü 2024-10-15 170212](https://github.com/user-attachments/assets/c1ec1e4e-07b8-443b-ba2d-27d8fee66be6)
Think you'll need to update eIBC.
![Ekran görüntüsü 2024-10-15 170201](https://github.com/user-attachments/assets/a5a8f917-fc4c-4a8a-9854-4a8d8bd36117)
![Ekran görüntüsü 2024-10-15 170139](https://github.com/user-attachments/assets/06c1ba36-b6e6-40c3-98d1-9c2e04e7509c)
![Ekran görüntüsü 2024-10-15 151931](https://github.com/user-attachments/assets/f4158a98-a4c4-4010-a6be-49d7a179a31f)

### Log Files

[relayer.log](https://github.com/user-attachments/files/17379472/relayer.log)

**Comment by artemijspavlovs** [comment]
this is expected, with the new features of dymension - you have to claim the ibc transfers. I believe the claim functionality was already introduced on the UI
