### ISSUE TITLE
Problem with transaction when using ledger with MM or Rabby wallet

### ISSUE THREAD

**Issue by Melix85** [dymensionxyz/roller#1077]
### Roller version

Ledger and MM [roblem

### Rollpp type (EVM/WASM) and version

evm

### OS

MM/Ledger

### Processor Architecture

MM/Ledger

### Steps to reproduce it

Hi, there is problem on your page. Anyone who is using ledger with MM or Rabby can't do any transaction (stake/collect).
there is message: transaction rejected by user but I don't even got confirmation on ledger. Blind sign is ON and MM version is the newest(12.4.1.) Already couple people write about this problem on your discord aswell.

### Expected result

Hi, there is problem on your page. Anyone who is using ledger with MM or Rabby can't do any transaction (stake/collect).
there is message: transaction rejected by user but I don't even got confirmation on ledger. Blind sign is ON and MM version is the newest(12.4.1.) Already couple people write about this problem on your discord aswell.

### Actual result

Hi, there is problem on your page. Anyone who is using ledger with MM or Rabby can't do any transaction (stake/collect).
there is message: transaction rejected by user but I don't even got confirmation on ledger. Blind sign is ON and MM version is the newest(12.4.1.) Already couple people write about this problem on your discord aswell.

### Log Files

Hi, there is problem on your page. Anyone who is using ledger with MM or Rabby can't do any transaction (stake/collect).
there is message: transaction rejected by user but I don't even got confirmation on ledger. Blind sign is ON and MM version is the newest(12.4.1.) Already couple people write about this problem on your discord aswell.

### Notes

Hi, there is problem on your page. Anyone who is using ledger with MM or Rabby can't do any transaction (stake/collect).
there is message: transaction rejected by user but I don't even got confirmation on ledger. Blind sign is ON and MM version is the newest(12.4.1.) Already couple people write about this problem on your discord aswell.

**Comment by artemijspavlovs** [comment]
communication regarding this issue is done in this discord forum post:

https://discord.com/channels/956961633165529098/1295999537445470208
