### ISSUE TITLE
Roller Setup Error

### ISSUE THREAD

**Issue by okannako** [dymensionxyz/roller#1082]
### Roller version

v1.7.1-alpha-rc01

### Rollpp type (EVM/WASM) and version

v2.2.0-rc01-56-g147382a

### OS

Ubuntu 20.04

### Processor Architecture

x86

### Steps to reproduce it

https://docs.dymension.xyz/run/operate/sequencer

### Expected result

When I entered this code, it should be able to set up the sequencer (roller rollapp setup)

### Actual result

 ERROR   you can't setup a node for nakoturk_2024-1 right now

**Comment by artemijspavlovs** [comment]
most likely a rollapp without iro, was already handled
