### ISSUE TITLE
[Feature Request]: rollapp Playground phase 2

### ISSUE THREAD

**Issue by OneNov0209** [dymensionxyz/roller#1083]
![Screenshot_2024-10-24-18-26-51-016_com server auditor ssh client-edit](https://github.com/user-attachments/assets/c2de05ce-6a21-48a7-9295-6021f3d08940)
### Implementation ideas

hello i participated in Playground phase 2 event here are my tokens: https://playground.dymension.xyz/rollapps/onenov_1291-1-1/token
![Screenshot_2024-10-24-18-08-51-053_com server auditor ssh client-edit](https://github.com/user-attachments/assets/aafef1e1-399e-476c-9dab-7089c282ac63)
Thanks

**Comment by artemijspavlovs** [comment]
da light client not started, run `roller da-light-client start`
