### ISSUE TITLE
Relayer issue - exit status 1, stderr: Error: rpc error: code = InvalidArgument desc = failed to load state at height 0

### ISSUE THREAD

**Issue by xhinis** [dymensionxyz/roller#1086]
### Roller version

1.7.1-alpha-rc01

### Rollpp type (EVM/WASM) and version

EVM

### OS

22.04.5 LTS (GNU/Linux 5.15.0-25-generic x86_64)

### Processor Architecture

AMD EPYC 7282 16-Core Processor

### Steps to reproduce it

I reinstalled everything i had the same problems everytime at step roller relayer setup

### Expected result

Expecting to relayer is working

### Actual result

root@vmi2168057:~# roller relayer setup
 INFO  existing roller configuration found, retrieving RollApp ID from it
the retrieved rollapp ID is: darksunrayz_10108-1, would you like to initialize the relayer for this rollapp? [y/N]: Yes
 SUCCESS  'darksunrayz_10108-1' is a valid RollApp ID
 INFO  relayer already initialized
 ▄ loading active IBC channels (0s)
  ERROR   failed to load active channel, command execution failed: exit status 1, stderr: Error: rpc error: code = InvalidArgument desc = failed to load state at height 0; no commit info found (latest height: 0): invalid request
          Usage:
            rollapp-evm query ibc connection connections [flags]
          
          Examples:
          rollapp-evm query ibc connection connections
          
          Flags:
                --count-total        count total number of records in connection ends to query for
                --grpc-addr string   the gRPC endpoint to use for this chain
                --grpc-insecure      allow gRPC over insecure channels, if not TLS the server must use TLS
                --height int         Use a specific height to query state at (this can error if the node is pruning state)
            -h, --help               help for connections
                --limit uint         pagination limit of connection ends to query for (default 100)
                --node string        <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
                --offset uint        pagination offset of connection ends to query for
            -o, --output string      Output format (text|json) (default "text")
                --page uint          pagination page of connection ends to query for. This sets offset to a multiple of limit (default 1)
                --page-key string    pagination page-key of connection ends to query for
                --reverse            results are sorted in descending order
          
          Global Flags:
                --chain-id string     The network chain ID
                --home string         directory for config and data (default "/root/.rollapp_evm")
                --log_format string   The logging format (json|plain) (default "plain")
                --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
                --trace               print out full stack trace on errors

### Log Files

[logs.txt](https://github.com/user-attachments/files/17519228/logs.txt)
[rollapp.txt](https://github.com/user-attachments/files/17519230/rollapp.txt)

### Notes

I checked them, these are working. 

dymrollapp-rpc.dksnodes.online
dymrollapp-api.dksnodes.online
dymrollapp-evm.dksnodes.online

root@vmi2168057:~# roller rollapp status
💈 The Rollapp sequencer is running on your local machine!

💈 RollApp ID: darksunrayz_10108-1
💈 Node ID: 12D3KooWNR3nVAC5KiDenEirnwmYzv7FHAKFgPRvj41mV9y4yoTR

💈 Endpoints:

Node RPC: http://0.0.0.0:26657
Rest API: http://0.0.0.0:1317

💈 Filesystem Paths:

Rollapp root dir:  /root/.roller/rollapp
Log file path:  /root/.roller/rollapp/rollapp.log

💈 Process Info:

PID:  660010

💈 Wallet Info:

Sequencer Address: dym1xyle03aqh99nrvawm6jmzxgsz2xj8vclu85hye
Sequencer Balance: 1990000000000000000adym
  ERROR   failed to retrieve DA address

**Comment by artemijspavlovs** [comment]
hello, 

an answer to this problem was provided on discord (to a different user), please refer to this message:

https://discord.com/channels/956961633165529098/1301152646698238055/1304069439217602660
