### ISSUE TITLE
Add roller hotfix command to apply a binary upgrade

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#1088]
We should be able to push fast binary upgrades which include only dymint with the assumption that they are not consensus breaking (i.e one node can upgrade without dependency for others).

Based on this research: https://www.notion.so/dymension/Rethinking-DRS-Implementation-12ba4a51f86a8008afa5de9998671010?pvs=4

We should describe the command and the flow in the roller design doc and get it reviewed before implementation

**Comment by artemijspavlovs** [comment]
everything will be handled via [#1088](https://github.com/dymensionxyz/roller/issues/1088)
