### ISSUE TITLE
IRO TOKEN SALE PERIOD BUG & BLOCK HEIGHT "0" BUG

### ISSUE THREAD

**Issue by geocmsk** [dymensionxyz/roller#1096]
### Roller version

💈 Roller version 1.7.2-alpha-rc03 💈 Build time: 2024-10-30T08:25:14Z 💈 Git commit: bf475f9e4917220aa7280a6eb81fc525037698de

### Rollpp type (EVM/WASM) and version

v2.2.0-rc01-56-g147382a

### OS

ubuntu-16gb-hel1-1

### Processor Architecture

x86_64

### Others

![image](https://github.com/user-attachments/assets/679865d9-cb55-4ffb-b789-697f9a90dfbd)

### Steps to reproduce it

![image](https://github.com/user-attachments/assets/c69ee8fd-dbe4-4254-926d-a3b8f84b54ba)
IRO token sale is still ongoing despite being set for 1 day. (Rollapp was established 1 week-10 days ago).

![image](https://github.com/user-attachments/assets/5f27434a-3d73-49b8-9e84-7223cbc5146e)
During the installation, the relayer address was not initially provided by the system for funding. Later, when the installation was done from the beginning, it was provided and the address was funded, but this time, although the RPC was healthy, an RPC error and block height "0" error output was seen.

### Expected result

As a result, I have not been able to activate my rollapp since the day Phase2 IRO started.

### Actual result

As a result, I have not been able to activate my rollapp since the day Phase2 IRO started. Since we have a limited amount of faucet rights, I do not have the chance to delete and install again.

I request your support in this matter, I have full confidence that you will conclude it quickly.

**Comment by artemijspavlovs** [comment]
this issue was answered on our discord, please refer to this as one of the messages:

https://discord.com/channels/956961633165529098/1301152646698238055/1304069439217602660
