### ISSUE TITLE
roller prints metadata on sequencer run

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/roller#138]
New output:
```
💈 The Rollapp sequencer is running on your local machine!
💈 Default endpoints:
💈 EVM RPC: http://0.0.0.0:8545
💈 Node RPC: http://0.0.0.0:26657
💈 Rest API: http://0.0.0.0:1317
💈 Log file path:  /Users/mtsitrin/.roller_local_interactive/rollapp/rollapp.log
💈 To interact with the rollapp through CLI:
 /Users/mtsitrin/Applications/dymension/rollapp/build/rollapp_evm --home /Users/mtsitrin/.roller_local_interactive/rollapp keys list --keyring-backend test
```

vs old output:
```
💈 The Rollapp sequencer is running on your local machine!
💈 EVM RPC: http://0.0.0.0:8545
💈 Node RPC: http://0.0.0.0:26657
💈 Rest API: http://0.0.0.0:1317
```

**Comment by mtsitrin** [comment]
I think similiar output should be for the relayer and sequencer on `roller run` as well

**Comment by omritoptix** [comment]
IMO the interact example may not be the clearest as it's a specific command which doesn't give him all the CLI options.
Assuming he follows the docs maybe I'd just print the cli binary so he can investigate it by himself vs giving him a specific keys command. 

Also is there a reason not to add the binary to the path/create an alias? I think showing him `rollapp_evm` as as binary is much cleaner. 

Maybe the cleanest way would be to create an alias like `alias rollapp_evm='/Users/mtsitrin/Applications/dymension/rollapp/build/rollapp_evm --home /Users/mtsitrin/.roller_local_interactive/rollapp '`

and then we can do something along the lines of: 

```
💈 The Rollapp sequencer is running on your local machine!
💈 Default endpoints:
💈 EVM RPC: http://0.0.0.0:8545
💈 Node RPC: http://0.0.0.0:26657
💈 Rest API: http://0.0.0.0:1317
💈 CLI binary: rollapp_evm
💈 Log file: /Users/mtsitrin/.roller_local_interactive/rollapp/rollapp.log
```

**Comment by mtsitrin** [comment]
I've used the `keys list` command to show the directory of the rollapp config
it required to use the CLI tool for txs

Just thought it's better than some random tx example
What u suggest for the CLI example? remove it?

regarding the path, I've used custom binary, by default it's `/usr/bin/roller/rollapp_evm`
I think it's fine and less error prune

**Comment by omritoptix** [comment]
> I've used the keys list command to show the directory of the rollapp config
> it required to use the CLI tool for txs

yes I understand but I think it's not clear for the user using it for the first time. An example anyway will be provided in the docs/in the CLI help,  so I think it's redundant. 


> regarding the path, I've used custom binary, by default it's /usr/bin/roller/rollapp_evm
> I think it's fine and less error prune

If it's a small effort I'd rather add it to path/alias as IMO it's annoying to copy paste it every time. 
Alternatively we can add an explanation on how to add it to path/alias in the docs and leave it as is. 

Either way I think it should be handled and not left like that.

**Comment by mtsitrin** [comment]
I'll print only logPath and rollapp home path
