### ISSUE TITLE
Add network flag for the init (and interactive)

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#146]
Users should be able to choose amongst the different network options in the init stage.
Currently the options should be:
devnet (default) 

Next step we'll add: 
localhost (should run mock).
Froopyland

**Comment by ItayLevyOfficial** [comment]
there is currently a --hub flag with devnet and local..?

**Comment by mtsitrin** [comment]
The mock support for localhost needs to be developed

will be very simple after
#112 
#110

**Comment by omritoptix** [comment]
@ItayLevyOfficial `--hub-network` flag where currently only `devnet` network is supported.
`devnet` network id is `devnet_304-1` and devnet rpc default endpoint `https://dymension.devnet.api.silknodes.io/`
