### ISSUE TITLE
Add assets list to release 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#148]
In order to support linux and darwin,  arm and amd we should have an assets list with each release which includes the following:

1. roller_v0.0.0_checksums.txt
2. roller_v0.0.0_darwin_amd64.tar.gz 
3. roller_v0.0.0_darwin_arm64.tar.gz 
4. roller_v0.0.0_linux_amd64.tar.gz 
6. source code (zip)
7. source code (tar.gz)

We need it before MVP (even if done manually currently).

**Comment by mtsitrin** [comment]
we might consider using something like: https://github.com/goreleaser/goreleaser

In the meanwhile I;ve created a script, it's in the branch

**Comment by mtsitrin** [comment]
I suggest, for currently unsupported OS/Arch, to run the `git clone`, `make install` for each of the required components

**Comment by omritoptix** [comment]
As agreed we'll use your script to manually generate releases until we automate it
