### ISSUE TITLE
roller run shows sequencer as stopped, but it stuck in reset loop

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/roller#154]
In case the sequencer failed to start,
the `roller run` command show its status as `Stopped`

But actully the sequencer is stuck in reset loop

**Comment by mtsitrin** [comment]
The `run` command have busy loop for retrying to bring up the components
It doesn't show the `stderr` of the failed component, nor having some backoff mechanism for retries

It just burns CPU cycles

Easy to reproduce when running unregistered rollapp

**Comment by omritoptix** [comment]
As I think the height and it's timestamp represents the status #217 (we can add a cron to check if hasn't been updated for a while add another status indication).  don't think following the process restarts cycle itself  is necessary

**Comment by mtsitrin** [comment]
The focus was on the **busy loop** in case it fails to start
I've added `5 Sec` delay in the meanwhile

I think the status does reflect whether it manages to bind the ports
