### ISSUE TITLE
Add support for mock da

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#165]
This should be last in the list of DAs

**Comment by mtsitrin** [comment]
But we don't want rollapp to register on devnet with mock DA

I think we should limit mock DA to local only

the question is whether we want local to have the hub mock

@yishay-dym

**Comment by mtsitrin** [comment]
split this task to #179 


This issue allows to actually run the rollapp with mockDA
#179 will handle the `run` command output, as there are Celestia related info hardcoded
