### ISSUE TITLE
Coin Type is hardcoded for 118 for custom rollapps, will not work for custom EVM rollapps

### ISSUE THREAD

**Issue by ItayLevyOfficial** [dymensionxyz/roller#196]
When generating a RollApp relayer key, the system defaults to coin type 118 for custom RollApps. This becomes an issue when a user is building a custom EVM (Ethereum Virtual Machine) RollApp, which actually requires a coin type of 60 for the 'ethsecp' key generation algorithm to work correctly. In the current setup, even if the custom RollApp is an EVM type and needs coin type 60, the system will still default to coin type 118, resulting in the incorrect key generation algorithm being used in the relayer.

**Comment by mtsitrin** [comment]
@ItayLevyOfficial
I suggest:
* adding type flag (EVM by default)
* In interactive mode, have {template EVM, custom EVM, custom Non-EVM}

This way u'll know what type of relayer key to initilize
