### ISSUE TITLE
Running relayer to connect to different ports

### ISSUE THREAD

**Issue by tecnodes-network** [dymensionxyz/roller#255]
### Roller version

latest

### OS

ubuntu 22.04

### Processor Architecture

x64

### Steps to reproduce it

n/a

### Expected result

n/a

### Actual result

n/a

### Notes

Since discord team ask them open the issue therefore i am writing here, it's not  bug but a question.

i am running another cosmos node on the machine where i am installing rollapp. 

for da-client & sequencer i changed the ports in config.yaml and they started.

but relayer is giving issue, it seems it's hardcoded to port 26657, i changed the port in

~/.roller/relayer/config/config.toml  to rpc-addr: http://localhost:46657

also tried to use

roller relayer start --node "tcp://localhost:46657" but it says: Error: unknown flag: --node

do i miss some other place to update the port?

**Comment by omritoptix** [comment]
thanks @tecnodes-network . should be closed soon and a new version with configurable rpc would get released.
