### ISSUE TITLE
Add support for easily running roller services in background

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#264]
We want to be able to allow users running on remote machines to easily run the roller services in the background.
One simple option could be using systemd and wrap the different services in a service file and exposing roller commands/flags to set it up.

One possible idea could be having a `roller service create` command  which create service files for all relevant services and `roller service create <some-service>` creates a service file only for this specific service.

Later we can either have the user run the services with systemd for example.

**Comment by VictorTrustyDev** [comment]
I have tried run it as systemd service on a Ubuntu 22 machine but it was not work. TTY issue or smt like that
