### ISSUE TITLE
Allow monitoring a rollapp deployed with roller

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#265]
roller should support starting a prometheus server which will present metrics from the various services.
e.g `roller start metrics-server`

**Comment by ItayLevyOfficial** [comment]
I think I will go with roller `metrics` start

**Comment by omritoptix** [comment]
As agreed  at least for phase 1 we'll start by providing users with instructions on how to install the relevent metric server and roller will not support it out of the box.
