### ISSUE TITLE
Some users complaining metamask doesn't work for them

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#273]
We need to double down on this and try to understand the RC

**Comment by VictorTrustyDev** [comment]
In my side, metamask works well for ETH Json RPC service (:8545) exposed by the RollApp EVM.

**Comment by omritoptix** [comment]
#274 should handle it. @ItayLevyOfficial, if the users complained will report it worked now. this issue can be closed.

**Comment by ItayLevyOfficial** [comment]
solved by #274
