### ISSUE TITLE
[Feature Request]: Faucet Request Time Problem

### ISSUE THREAD

**Issue by kriptoescobar007** [dymensionxyz/roller#279]
### Implementation ideas

I have a problem. I set up a roller node. I have done the necessary actions. the last thing left was to request my faucet token with a request to my wallet. i used correct code but tx failed because i sent small amount of tokens. then i sent a lot from my own token via node rollers.

and I wanted to attract it again with the faucetten request code, but unfortunately the limit time set is too long.

I'll post the error;

You can request Kriptoescobar_1905-23 tokens no more than once every 168 hours, please try again in 167 hours
any chance to fix this? Could it be shorter? As a result, we may have used the request command incorrectly. Need help with this.

**Comment by omritoptix** [comment]
thank you @kriptoescobar007. We'll look into it and think about the best UI for requesting rollapp tokens through the faucet.
