### ISSUE TITLE
unable to send ibc transfer

### ISSUE THREAD

**Issue by gsweeh** [dymensionxyz/roller#297]
### Roller version

v0.1.3

### OS

Ubuntu

### Processor Architecture

x86_64

### Others

24gb 2tb 

### Steps to reproduce it

rollapp_evm tx ibc-transfer transfer transfer channel-0 dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz 1000000000000000000uGSH --from rollapp_sequencer --keyring-backend test --home ~/.roller/rollapp --broadcast-mode block

### Expected result

the transaction to work, and the faucet to be filled

### Actual result

rollapp_evm tx ibc-transfer transfer transfer channel-0 dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz 1000000000000000000uGSH --from rollapp_sequencer --keyring-backend test --home ~/.roller/rollapp --broadcast-mode block
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = port-id: transfer, channel-id: channel-0: channel not found: key not found
Usage:
  rollapp_evm tx ibc-transfer transfer [src-port] [src-channel] [receiver] [amount] [flags]
Examples:
rollapp_evm tx ibc-transfer transfer [src-port] [src-channel] [receiver] [amount]
Flags:
      --absolute-timeouts               Timeout flags are used as absolute timeouts.
  -a, --account-number uint             The account number of the signing account (offline mode only)
      --aux                             Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string           Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                         ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string              Fee granter grants fees for the transaction
      --fee-payer string                Fee payer pays fees for the transaction
instead of deducting from the signer
      --fees string                     Fees to pay along with transaction; eg:
10uatom
      --from string                     Name or address of private key with which to sign
      --gas string                      gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can
be used instead of "fees". (default 200000)
      --gas-adjustment float            adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually
this flag is ignored  (default 1)
      --gas-prices string               Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only                   Build an unsigned transaction and write
it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                            help for transfer
      --keyring-backend string          Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string              The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                          Use a connected Ledger device
      --memo string                     Memo to be sent along with the packet.
      --node string                     <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
      --note string                     Note to add a description to the transaction (previously --memo)
      --offline                         Offline mode (does not allow any online
functionality)
  -o, --output string                   Output format (text|json) (default "json")
      --packet-timeout-height string    Packet timeout block height. The timeout is disabled when set to 0-0. (default "0-1000")
      --packet-timeout-timestamp uint   Packet timeout timestamp in nanoseconds
from now. Default is 10 minutes. The timeout is disabled when set to 0. (default 600000000000)
  -s, --sequence uint                   The sequence number of the signing account (offline mode only)
      --sign-mode string                Choose sign mode (direct|amino-json|direct-aux), this is an advanced feature
      --timeout-height uint             Set a block timeout height to prevent the tx from being committed past a certain height
      --tip string                      Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
  -y, --yes                             Skip tx broadcasting prompt confirmation
Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/root/.rollapp_evm")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
![Screenshot_2023-07-20-13-38-05-272_com server auditor ssh client](https://github.com/dymensionxyz/roller/assets/65717972/b9c72dd0-9ee5-4736-b8bd-42964346df29)

### Relevant log output

```Shell
rollapp_evm tx ibc-transfer transfer transfer channel-0 dym12ad4lux36lta7d75v2w6je2y386y9s5xp658pz 1000000000000000000uGSH --from rollapp_sequencer --keyring-backend test --home ~/.roller/rollapp --broadcast-mode block
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = port-id: transfer, channel-id: channel-0: channel not found: key not found
Usage:
  rollapp_evm tx ibc-transfer transfer [src-port] [src-channel] [receiver] [amount] [flags]
Examples:
rollapp_evm tx ibc-transfer transfer [src-port] [src-channel] [receiver] [amount]
Flags:
      --absolute-timeouts               Timeout flags are used as absolute timeouts.
  -a, --account-number uint             The account number of the signing account (offline mode only)
      --aux                             Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string           Transaction broadcasting mode (sync|async|block) (default "sync")
      --dry-run                         ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string              Fee granter grants fees for the transaction
      --fee-payer string                Fee payer pays fees for the transaction
instead of deducting from the signer
      --fees string                     Fees to pay along with transaction; eg:
10uatom
      --from string                     Name or address of private key with which to sign
      --gas string                      gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can
be used instead of "fees". (default 200000)
      --gas-adjustment float            adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually
this flag is ignored  (default 1)
      --gas-prices string               Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only                   Build an unsigned transaction and write
it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                            help for transfer
      --keyring-backend string          Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string              The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                          Use a connected Ledger device
      --memo string                     Memo to be sent along with the packet.
      --node string                     <host>:<port> to tendermint rpc interface for this chain (default "tcp://localhost:26657")
      --note string                     Note to add a description to the transaction (previously --memo)
      --offline                         Offline mode (does not allow any online
functionality)
  -o, --output string                   Output format (text|json) (default "json")
      --packet-timeout-height string    Packet timeout block height. The timeout is disabled when set to 0-0. (default "0-1000")
      --packet-timeout-timestamp uint   Packet timeout timestamp in nanoseconds
from now. Default is 10 minutes. The timeout is disabled when set to 0. (default 600000000000)
  -s, --sequence uint                   The sequence number of the signing account (offline mode only)
      --sign-mode string                Choose sign mode (direct|amino-json|direct-aux), this is an advanced feature
      --timeout-height uint             Set a block timeout height to prevent the tx from being committed past a certain height
      --tip string                      Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
  -y, --yes                             Skip tx broadcasting prompt confirmation
Global Flags:
      --chain-id string     The network chain ID
      --home string         directory for config and data (default "/root/.rollapp_evm")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```

**Comment by gsweeh** [comment]
![Screenshot_2023-07-20-16-39-51-438_com server auditor ssh client](https://github.com/dymensionxyz/roller/assets/65717972/e2816b23-7a83-456f-9b86-5cdb32808ace)
![Screenshot_2023-07-20-16-38-28-409_com server auditor ssh client](https://github.com/dymensionxyz/roller/assets/65717972/f80d7671-2859-47b6-a56d-ecd676e6a4be)

**Comment by omritoptix** [comment]
thanks. from the log it seems like the channel and port weren't created because the relayer couldn't reach the sequencer. can you verify the sequencer is indeed running and available on port 26657?
you can do it by running `curl http://localhost:26657/status`

**Comment by gsweeh** [comment]
![Screenshot_2023-07-20-21-05-52-468_com server auditor ssh client](https://github.com/dymensionxyz/roller/assets/65717972/32f78dd1-c61e-44b7-9f39-896d00d6890e)

**Comment by omritoptix** [comment]
can you send over please the sequencer logs?

**Comment by gsweeh** [comment]
Any command?

**Comment by omritoptix** [comment]
the sequencer log file path should appear in the roller output. so just take the file and post it here if possible.

**Comment by gsweeh** [comment]
roller relayer start
Error: context deadline exceeded
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel
-0 -l 1 --home /root/.roller/relayer exited with error:  Error: channel{channel-
0} not found for [gsweeh_2004-1] -> client{07-tendermint-0}@connection{connectio
n-0}
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel
-0 -l 1 --home /root/.roller/relayer exited with error:  Error: channel{channel-
0} not found for [gsweeh_2004-1] -> client{07-tendermint-0}@connection{connectio
n-0}
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel
-0 -l 1 --home /root/.roller/relayer exited with error:  Error: channel{channel-
0} not found for [gsweeh_2004-1] -> client{07-tendermint-0}@connection{connectio
n-0}
Cron command /usr/local/bin/roller_bins/rly tx update-clients hub-rollapp --home
 /root/.roller/relayer exited with error:  ts=2023-07-20T17:16:55.032896Z lvl=in
fo msg="Successful transaction" provider_type=cosmos chain_id=gsweeh_2004-1 gas_
used=120367 fees= fee_payer=ethm1p8vkpkfadpeysz4ygpl294kqye2nfj3nm2x995 height=1
8923 msg_types=/ibc.core.client.v1.MsgUpdateClient tx_hash=C37DBAC64854378DC1323
36CF9A8FA5BB30DA039C76E8BB2A5A5928C2564E590
ts=2023-07-20T17:17:01.993073Z lvl=info msg="Error building or broadcasting tran
saction" provider_type=cosmos chain_id=devnet_304-1 attempt=1 max_attempts=30 er
ror="rpc error: code = Unknown desc = rpc error: code = Unknown desc = TrustedHe
ight {1 18636} must be less than header height {1 18636}: invalid header height
[cosmos/ibc-go/v5@v5.2.0/modules/light-clients/01-dymint/types/header.go:72] Wit
h gas wanted: '0' and gas used: '200520' : unknown request"
ts=2023-07-20T17:17:19.257471Z lvl=info msg="Error building or broadcasting tran
saction" provider_type=cosmos chain_id=devnet_304-1 attempt=2 max_attempts=30 er
ror="rpc error: code = Unknown desc = rpc error: code = Unknown desc = TrustedHe
ight {1 18636} must be less than header height {1 18636}: invalid header height
[cosmos/ibc-go/v5@v5.2.0/modules/light-clients/01-dymint/types/header.go:72] Wit
h gas wanted: '0' and gas used: '147048' : unknown request"
ts=2023-07-20T17:17:24.787302Z lvl=info msg="Try to send messages one by one:" p
rovider_type=cosmos
ts=2023-07-20T17:17:24.787326Z lvl=info msg=/ibc.core.client.v1.MsgUpdateClient
provider_type=cosmos chain_id=devnet_304-1 seq=0
ts=2023-07-20T17:17:25.069523Z lvl=info msg=/ibc.core.client.v1.MsgUpdateClient
provider_type=cosmos chain_id=devnet_304-1 seq=0 error="context deadline exceede
d"
ts=2023-07-20T17:17:25.069552Z lvl=info msg="Failed sending transaction" chain_i
d=devnet_304-1 msg-0Error="unsupported value type" error="context deadline excee
ded"
ts=2023-07-20T17:17:25.069576Z lvl=info msg="Partial success when updating clien
ts" src_chain_id=gsweeh_2004-1 dst_chain_id=devnet_304-1 send_resultError="unsup
ported value type"
Error: context deadline exceeded
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel
-0 -l 1 --home /root/.roller/relayer exited with error:  Error: channel{channel-
0} not found for [gsweeh_2004-1] -> client{07-tendermint-0}@connection{connectio
n-0}
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel
-0 -l 1 --home /root/.roller/relayer exited with error:  Error: channel{channel-
0} not found for [gsweeh_2004-1] -> client{07-tendermint-0}@connection{connectio
n-0}
Cron command /usr/local/bin/roller_bins/rly tx relay-packets hub-rollapp channel

**Comment by mtsitrin** [comment]
It should be fixed in upcoming release (by https://github.com/dymensionxyz/roller/pull/308)

u can try for now to run
`/usr/local/bin/roller_bins/rly --home ~/.roller/relayer tx link -t 300s hub-rollapp`

LMK if it worked
