### ISSUE TITLE
This script not working for arm64 Linux

### ISSUE THREAD

**Issue by gsweeh** [dymensionxyz/roller#299]
### Roller version

v0.1.3

### OS

Ubuntu

### Processor Architecture

aarch64

### Steps to reproduce it

curl -L https://dymensionxyz.github.io/roller/install.sh | bash

### Expected result

It should install rollerapp required package and etc..

### Actual result

 curl -L https://dymensionxyz.github.io/roller/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:100  1415  100  1415    0     0  20143      0 --:--:-- --:--:-- --:--:-- 20214
💈 Downloading roller...
curl: (3) URL using bad/illegal format or missing URL
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
![Screenshot_2023-07-23-11-50-14-495_com server auditor ssh client](https://github.com/dymensionxyz/roller/assets/65717972/57d1e8c3-5920-439c-b368-23d39354f307)

**Comment by mtsitrin** [comment]
closed by #302
