### ISSUE TITLE
register a dym-ibc token for evm rollapp on genesis

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#339]

**Comment by VictorTrustyDev** [comment]
IBC denom generation algo: `"ibc/" + sha256(port + "/" + channel + "/" + base_denom)` (see [this](https://tutorials.cosmos.network/tutorials/6-ibc-dev/))

That means, the denom of the ibc coins are dynamically based on the chanel id (while port generally hardcoded to "transfer") so I think this task is not really possible to have a correct implementation.

**Comment by mtsitrin** [comment]
Hi @VictorTrustyDev, thx for the feedback
We're well aware of this.

We'll pre-assume the channel to be `channel-0`, which is correct in most of the cases for rollapps created with `roller`.

For other edge cases, or to register other tokens, it will be required to register the token manually, as will be described in the docs

**Comment by mtsitrin** [comment]
@omritoptix closing it for now.
short-term will be handled by docs
long-term will be auto-registration of new IBC tokens
