### ISSUE TITLE
roller sequencer start should output the current status

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/roller#430]
`roller sequencer start ` should have periodic output of the metrics (height, hub height)

also should output if the rollapp is unhealthy

can be implemented as
`roller sequencer status`

**Comment by mtsitrin** [comment]
in 2nd thought, it;s better to be part of the `sequencer start`
this way, it will be shown in the `systemd` logs as well

**Comment by ItayLevyOfficial** [comment]
problematic because it makes the sequencer start heavier, I think I'll keep it in a separate command
