### ISSUE TITLE
Relayer service Bech32 Address prefix error

### ISSUE THREAD

**Issue by bertugkara** [dymensionxyz/roller#463]
![Screenshot_2023-08-24_at_00 05 54](https://github.com/dymensionxyz/dymension/assets/90678773/32cb9546-c02f-480e-9349-52424a91b397)

The error happened whenever I try to run Relayer service. I rebuilt my VPS without any log backup so that I will not be able to provide you any logs. After rebuild and fresh install, it worked fine.

**Comment by mtsitrin** [comment]
@ItayLevyOfficial familiar with this issue?

**Comment by ItayLevyOfficial** [comment]
no @mtsitrin. @bertugkara can you share more details about your rollapp deployment?

**Comment by bertugkara** [comment]
> 

@ItayLevyOfficial as I mentioned I do not have any backups but I will try to explain as much as I can remember.

I was trying to run validator and rollapp deployment on a same machine in a powerful VPS.
I first deployed a validator, after I tried to deploy rollapp, couldn't manage it. 

Step 1 : Installed Go
Step 2: fetched dymension repo, checked out to branch v1.0.2-beta
Step 3: performed make install on dymension's directory
Step 4: initialized node using dymd init
Step 5: ran the dym as systemd service
Step 6: created wallet using command `dymd keys add wallet`
Step 7: After synced, created validator.

Step 8: fetched Roller.
Step 9: initialized the roller then got the tokens using faucets. then I registered roller.
Step 10: ran the roller on new terminal Screen using both "roller run" or different systemd services (never succeed, I got the error above.)
That was the general flow.
Now I consider may be wallet addresses of validator and roller crossed or corrupted/overwrote each other. 
Then I rebuilt my VPS, installed only Roller, worked fine for a while but after sometime I lost channels.
I hope I could explain myself. 
Please do not hesitate for further questions.

**Comment by mtsitrin** [comment]
@bertugkara have u changed the rollapp's RPC ports?

**Comment by bertugkara** [comment]
> @bertugkara have u changed the rollapp's RPC ports?

@mtsitrin As far as I remember, no I didn't.

**Comment by mtsitrin** [comment]
from the error, it seems to me that dymd is running in the background on port 26657
possible?

**Comment by omritoptix** [comment]
closing as stale.
