### ISSUE TITLE
Run connection/channel attempt only after block advancement in both chains

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#465]
### Problem

1. Assume connection/channel failure happens (DA, hub etc)
2. When starting connection or channel we look for the last block for any messages (we assume that a block was advanced as supposed to be fast blocks and by that only get relevant messages for current attempt)
3. Unlike tendermint chains, As block production rate could be slow (due to empty blocks feature), and the block height may not advance, when querying for the last block we may pick up old handshake messages.
4. At this point the relayer starts relaying all new and previous handshake messages as they all pass the filter of relevant messages for the client id.
5. Regardless to the stage we are at, the relayer keeps checking for termination condition. The first handshake that completes (most likely and old handshake will complete first) it will end up the handshake process for the current handshake.
6. At the end you have old channels/connections being open and current channel attempt not succeeding. 
7. This creates a failure loop.

The relayer was built with the assumption of fast blocks so this situation should be rare to occur. 

### Solution

To prevent from handling old messages, make sure before each attempt that each chain advanced at least one block

**Comment by mtsitrin** [comment]
@omritoptix 
does only the rollapp needs to advance or the stateUpdate on the hub needs to advance?

because we run updateClient in the background, before creating connection and channel, the rollapp height does supposed to increase
