### ISSUE TITLE
[Feature Request]: Why can't I do the fork on github?

### ISSUE THREAD

**Issue by TriNguyen79** [dymensionxyz/roller#534]
### Implementation ideas

i did a fork on the project's github but it failed, it turned to a blank page
![5A512EE3-E35F-488A-8BE0-FA0089714551](https://github.com/dymensionxyz/roller/assets/105418732/82902d56-377a-4485-867c-bde95034b9c9)

**Comment by ItayLevyOfficial** [comment]
Not related to roller.
