### ISSUE TITLE
[Feature Request]: Port 2121

### ISSUE THREAD

**Issue by AviaOne** [dymensionxyz/roller#538]
### Implementation ideas

The port 2121 is used with the Celestia's Bridge and making direct conflict if we want install Dymension Rollapp on the same server because Dymension Rollapp is using the port 2121 as well.
To avoid to change this manually directly in the file, use an other port like 2222 will make the things more simple.

**Comment by omritoptix** [comment]
Hi @AviaOne, can you elaborate please on which dymension service uses port 2121? (i.e it's not the rpc,api or grpc)

**Comment by AviaOne** [comment]
Please go to this file -> /.roller/da-light-node/config.toml
Start from Ligne 14
```
[P2P]
  ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
  AnnounceAddresses = []
  NoAnnounceAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1", "/ip4/127.0.0.1/udp/2121/quic-v1", "/ip6/::/udp/2121/quic-v1", "/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
  MutualPeers = []
  PeerExchange = false
  RoutingTableRefreshPeriod = "1m0s"
  [P2P.ConnManager]
    Low = 50
    High = 100
    GracePeriod = "1m0s"
```
This port 2121 is used by Celestia Bridge, Dymension can replace it by 2222 to be able to run on the same server

**Comment by AviaOne** [comment]
Maybe it will be more clear with these screenshot
When you already make running Celestia Bridge and want to install Dymension Rollup
https://snipboard.io/29kzjH.jpg
See the port 2121 non available to make running Dymension Rollup
https://snipboard.io/H4OUNL.jpg

**Comment by AviaOne** [comment]
????????????????????????

**Comment by AviaOne** [comment]
Are you still here ?

**Comment by ItayLevyOfficial** [comment]
Hey there. We have no control over the ports the celestia bridge is using.

**Comment by AviaOne** [comment]
thank you to teach me this, 
I was not asking this...
anyway that's ok, keep close this ticket, that's more simple...

**Comment by omritoptix** [comment]
Hi @AviaOne sorry for the late delay in response.

IMO running them both on the same machine is not a common use case hence the port changes can be made manually per your specific usecase.  

As a general approach we ideally prefer to align with the default Celestia light client configuration as much as possible to possibly avoid cascading changes and align with the common troubleshooting. 

Happy to get your feedback if you think otherwise.
