### ISSUE TITLE
Starting roller after upgrade from v0.1.15-beta to v.0.1.16-beta leads to a "no ID" error

### ISSUE THREAD

**Issue by boobcactus** [dymensionxyz/roller#549]
### Roller version

v0.1.16-beta

### OS

Debian GNU/Linux 12 (bookworm)

### Processor Architecture

x86_64

### Others

No resource limitations were observed. Server is using an Intel Xeon E3-1270 with 16GB RAM and 256gb SATA SSD. 

### Steps to reproduce it

Stopped roller services in systemd. 
Performed a roller update using `curl -L https://dymensionxyz.github.io/roller/install.sh | bash` which seemed to process correctly. 
Performed `roller migrate`, which also showed the latest version as expected. 
Attempted to start the service files again and view rollapp.log with `tail -f ~/.roller/rollapp/rollapp.log`. No output was recorded in the logs. 
Checked `sudo journalctl -u sequencer -f -ocat` and noticed the no ID error. 
Stopped service files again and tried to use `roller run`, but the issue persisted

### Expected result

Proper upgrade with no errors. I performed this from v0.1.14 to v0.1.15 with no issues. 

### Actual result

The roller appears to install the latest update just fine. But when I go to start (either with systemd or `roller run`, a "no ID" error is presented. Changing the DA layer to local does not help. 

### Relevant log output

```Shell
user@liberty-1:~/scripts/dymScripts$ curl -L https://dymensionxyz.github.io/roller/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1765  100  1765    0     0  25554      0 --:--:-- --:--:-- --:--:-- 25955
💈 Downloading roller...
######################################################################## 100.0%
💈 Installing roller...
💈 Installation complete! You can now use roller from your terminal.
user@liberty-1:~/scripts/dymScripts$ roller migrate
💈 Roller has migrated successfully to v0.1.16!
user@liberty-1:~/scripts/dymScripts$ roller run
💈 command execution failed: exit status 1, stderr: Error: wrong ID: no ID
Usage:
  dymd query bank balances [address] [flags]

Flags:
      --count-total        count total number of records in all balances to query for
      --denom string       The specific balance denomination to query for
      --grpc-addr string   the gRPC endpoint to use for this chain
      --grpc-insecure      allow gRPC over insecure channels, if not TLS the server must use TLS
      --height int         Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help               help for balances
      --limit uint         pagination limit of all balances to query for (default 100)
      --node string        <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
      --offset uint        pagination offset of all balances to query for
  -o, --output string      Output format (text|json) (default "text")
      --page uint          pagination page of all balances to query for. This sets offset to a multiple of limit (default 1)
      --page-key string    pagination page-key of all balances to query for
      --reverse            results are sorted in descending order

Global Flags:
      --chain-id string     The network chain ID (default "dymension")
      --home string         directory for config and data (default "/home/user/.dymension")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors


```

### Notes

I spoke with Itay and he observed the issue on my screen. He suggested the DA change to local, but no progress. He also suggested running `dymd config chain-id froopyland_100-1`, which did populate the chain-id field in the client config, but that was not the missing ID. When viewing the output of `roller config show`, everything appears as it did before the upgrade.

**Comment by boobcactus** [comment]
After downgrading to v0.1.15-beta, the issue persists

**Comment by boobcactus** [comment]
I will begin a resync of the rollapp per [this guide](https://mzonder.notion.site/DYMENSION-rollapp-resync-738b2927f2b049229ed5120207c4043c) and will update this thread if there are any issues.

**Comment by boobcactus** [comment]
I just encountered the no ID issue again, this time with a fresh rollapp. 
Here are my logs, with some notes below that:
```
user@liberty-1:~$ roller config set hub-rpc https://testnet-dymension-rpc.lavenderfive.com:443/
user@liberty-1:~$ roller run
2023/10/05 16:48:30 Connecting to wss://dymension-devnet.avail.tools/ws...
user@liberty-1:~$ roller config set hub-rpc https://froopyland.api.silknodes.io:443/
user@liberty-1:~$ roller run
2023/10/05 16:49:25 Connecting to wss://dymension-devnet.avail.tools/ws...
💈 command execution failed: exit status 1, stderr: Error: wrong ID: no ID
Usage:
  dymd query bank balances [address] [flags]

Flags:
      --count-total        count total number of records in all balances to query for
      --denom string       The specific balance denomination to query for
      --grpc-addr string   the gRPC endpoint to use for this chain
      --grpc-insecure      allow gRPC over insecure channels, if not TLS the server must use TLS
      --height int         Use a specific height to query state at (this can error if the node is pruning state)
  -h, --help               help for balances
      --limit uint         pagination limit of all balances to query for (default 100)
      --node string        <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
      --offset uint        pagination offset of all balances to query for
  -o, --output string      Output format (text|json) (default "text")
      --page uint          pagination page of all balances to query for. This sets offset to a multiple of limit (default 1)
      --page-key string    pagination page-key of all balances to query for
      --reverse            results are sorted in descending order

Global Flags:
      --chain-id string     The network chain ID (default "dymension")
      --home string         directory for config and data (default "/home/user/.dymension")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --trace               print out full stack trace on errors
```
# NOTES

I am trying to setup a new rollapp, and I'm past the point of `roller tx register` - that command succeeded.
But I waited nearly an hour for `roller run` to start the sequencer. 
Performing `roller sequencer start` will error the same, saying `Error: settlement layer client initialization error: rollappID: samanvay_8382652-1: no sequencer registered on the hub for this rollapp`.
I can confirm the sequencer is registered because trying to run `roller tx register` fails and informs me the ID already exists. 
So I decided to try switching my hub-rpc to lavender5's node, since I know theirs works (but is rate-limited).
You can see above where I try to set the hub-RPC to lavender5 and run `roller run`. It errors with the `no sequencer registered on the hub for this rollapp` error - same as Silk Node's RPC
After that failed, I decided I'd just go back to silk nodes, and I execute the `roller config set hub-rpc` command again
After switching back, the no ID error presents itself again, and I cannot start the roller's sequencer.

**Comment by boobcactus** [comment]
I see now that I accidentally set the REST API for Silk Nodes as my RPC endpoint. Im not certain this is the only reason for the error, but gives us something to check

**Comment by ItayLevyOfficial** [comment]
It appears to be an RPC issue, which was caused by our RPC provider mistakenly blacklisting certain addresses due to a suspected DDoS attack. He has since removed the legitimate IPs from the blacklist, so it should function normally now. I couldn't reproduce the bug on my local machine. Please try restarting the rollapp, @boobcactus.

**Comment by boobcactus** [comment]
Hey @ItayLevyOfficial! So the rollapp functions now with silknodes configured as hub-rpc. I also mistakenly set the rest API as the rpc, which was probably the cause of the "no ID" error and the 501 status code when executing `rollapp_evm`. 

Side note: I think there is an issue with trailing slashes causing the RPC to not connect on some calls, usually around first-time setup. After setting the rpc to `https://froopyland.rpc.silknodes.io:443/`, I had issues getting online, but after I removed that forward slash at the end, it seemed to work. 

I will attempt to spin up a test rollapp on a local machine and update this thread if that's an actual issue.

**Comment by boobcactus** [comment]
I'm closing this issue since the error has been dealt with. Regarding the forward slash in the hub-rpc url causing issues with querying - that may become its own issue if it becomes more relevant
