### ISSUE TITLE
DYM deposits can't be displayed on the rollapp front-end page, dym rewards no hair growth.

### ISSUE THREAD

**Issue by polibee** [dymensionxyz/roller#552]
### Roller version

0.1.6

### OS

ubuntu

### Processor Architecture

coinowo_3744361-1

### Steps to reproduce it

Depositing DYM on the front end of the web page does not show up, the chain confirms that the deposit was successful. iBC Transfers has a transaction history. reward score stays at 0.

### Expected result

Multiple deposits of DYM via keplr wallet but front end doesn't show up, ibc transfers are documented, wallet changed as well.

### Actual result

Multiple deposits of DYM via keplr wallet but front end doesn't show up, ibc transfers are documented, wallet changed as well.

**Comment by ItayLevyOfficial** [comment]
Hey there. Can you please share the sequencer and relayer logs?

**Comment by ItayLevyOfficial** [comment]
referenced at dymensionxyz/portal#170
