### ISSUE TITLE
The confirmation window on the deposit screen is stuck

### ISSUE THREAD

**Issue by Tarbay** [dymensionxyz/roller#562]
### Roller version

roller version

### OS

os

### Processor Architecture

amd

### Steps to reproduce it

After making a deposit, this window remains on the screen, it better disappear after the transaction is completed. ''IBC transfer successfully sent! View explorer  Explore!! Screenshot is attached.

### Expected result

n

### Actual result

n

**Comment by ItayLevyOfficial** [comment]
Opened an issue on the portal dymensionxyz/portal#169
