### ISSUE TITLE
log error sequencer

### ISSUE THREAD

**Issue by Coha05** [dymensionxyz/roller#563]
### Roller version

v0.1.17-beta

### OS

ubuntu 20

### Processor Architecture

x86_64

### install roller binaries

```bash
# export ROLLER_RELEASE_TAG="v0.1.17-beta"
curl -L https://dymensionxyz.github.io/roller/install.sh | bash
```

### init roller

```bash
# init roller
roller config init rollapp denom

# remove new created keys
rm -r $HOME/.roller/da-light-node/keys
rm -r $HOME/.roller/hub-keys
rm -r $HOME/.roller/relayer/keys
rm -r $HOME/.roller/rollapp/keyring-test
rm -r $HOME/.roller/rollapp/config
```

### download backup

```bash
# download backup
cd $HOME
wget **<OLD_SERVER_IP>**:8150/roller_keys_config_backup.tar

# untar
tar xvf roller_keys_config_backup.tar
```

### configure the node to run as non aggregator

```bash
# correct paths (in case USER has changed)
sed -i "s|^Home *=.*|Home = \"${HOME}/.roller\"|" $HOME/.roller/config.toml
sed -i "s|^keyring_home_dir *=.*|keyring_home_dir = \"${HOME}/.roller/hub-keys\"|" $HOME/.roller/rollapp/config/dymint.toml

# configure the node to run as non aggregator
sed -i 's/^aggregator *=.*/aggregator = "false"/' $HOME/.roller/rollapp/config/dymint.toml
```

### create services

```bash
tee $HOME/da-light-client.service > /dev/null <<EOF
[Unit]
Description=da-light-client
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/local/bin/roller da-light-client start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

tee $HOME/sequencer.service > /dev/null <<EOF
[Unit]
Description=sequencer
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/local/bin/roller sequencer start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

tee $HOME/relayer.service > /dev/null <<EOF
[Unit]
Description=relayer
After=network-online.target
[Service]
User=$USER
ExecStart=/usr/local/bin/roller relayer start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

sudo mv $HOME/da-light-client.service /etc/systemd/system/
sudo mv $HOME/sequencer.service /etc/systemd/system/
sudo mv $HOME/relayer.service /etc/systemd/system/

sudo systemctl enable da-light-client
sudo systemctl enable sequencer
sudo systemctl enable relayer

sudo systemctl daemon-reload

```

### Expected result

syncTarget is the last block

e.g.: level=info msg="Syncing until target[current height 1334 syncTarget 1436]" module=BlockManager

sync successful

### Actual result

time="2023-10-18T15:21:03Z" level=debug msg="indexed block txs[height 4 num_txs 0]" module=txindex
time="2023-10-18T15:21:03Z" level=info msg="Syncing until target[current height 4 syncTarget 533]" module=BlockManager
time="2023-10-18T15:21:03Z" level=debug msg="Getting batch from settlement layer[state index [3]]" module=settlement_client
time="2023-10-18T15:21:04Z" level=debug msg="trying to retrieve batch from DA[daHeight 605144]" module=BlockManager
time="2023-10-18T15:22:04Z" level=error msg="failed to retrieve batch from DA[daHeight 605144 error failed to retrieve batch: Get \"http://localhost:26659/namespaced_data/0000000000000000000000000000000000000000008b80cce7a9751046/height/605144\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]" module=BlockManager
time="2023-10-18T15:22:04Z" level=error msg="Failed to sync until target. error while processing next DA batch[error failed to retrieve batch: Get \"http://localhost:26659/namespaced_data/0000000000000000000000000000000000000000008b80cce7a9751046/height/605144\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]" module=BlockManager
time="2023-10-18T15:22:17Z" level=debug msg="WebSocket connection closed[]"
time="2023-10-18T15:22:22Z" level=debug msg="WebSocket connection closed[]"
time="2023-10-18T15:22:48Z" level=debug msg="EVM RPC reconnects to Tendermint WS[address tcp://0.0.0.0:26657/websocket]"
time="2023-10-18T15:22:54Z" level=debug msg="EVM RPC reconnects to Tendermint WS[address tcp://0.0.0.0:26657/websocket]"

**Comment by ItayLevyOfficial** [comment]
Hey there. Can you also add the DA logs? from `~/.roller/da-light-node/light_client.log`

**Comment by ItayLevyOfficial** [comment]
I would also simply archive and copy the entire roller config dir (`~/.roller`) instead of trying to copy the keys separately as it's error prone.

**Comment by ItayLevyOfficial** [comment]
Have you looked at https://docs.dymension.xyz/build/state_sync btw

**Comment by Coha05** [comment]
Solved it myself thanks. Thanks for the docs.
