### ISSUE TITLE
[Feature Request]: Uptime from the interface is wrong

### ISSUE THREAD

**Issue by AviaOne** [dymensionxyz/roller#567]
### Implementation ideas

In this screenshot  everything is ok, my rollapp making transaction when this interface (https://portal.dymension.xyz/rollapp/aviaonerollapp_2683399-1) flag my rollapp as offline.
![screenshot 2023-10-24](https://github.com/dymensionxyz/roller/assets/105792641/10c624a8-a16d-4728-8301-dd56c072622b)

This explorer ( https://fl.dymscan.live/rollapp/aviaonerollapp_2683399-1 ) is showing my rollapp as "Active Proposer" and showing transaction from my rollapp when the Interface from Dymension showing my rollapp OFFLINE.
![screenshot 2023-10-24 (2)](https://github.com/dymensionxyz/roller/assets/105792641/8722b387-747f-4e13-8b28-7e6928cd9d7e)

This happen not less than one time per day.
Just need to wait, touch nothing, and my rollapp is back online

How the uptime of my rollapp will be calculated ? with the data of portal.dymension.xyz ?

Thanks

**Comment by AviaOne** [comment]
Same time I would like suggest to add the statement Online - Offline directly on the rollapp page https://portal.dymension.xyz/rollapp/aviaonerollapp_2683399-1 and not only in the search field.

**Comment by ItayLevyOfficial** [comment]
Hey, just checked the portal and looks like it has been fixed. Can I close this? @AviaOne

**Comment by ItayLevyOfficial** [comment]
> Same time I would like suggest to add the statement Online - Offline directly on the rollapp page https://portal.dymension.xyz/rollapp/aviaonerollapp_2683399-1 and not only in the search field.

Re this - I opened an issue on the portal dymensionxyz/portal#171

**Comment by AviaOne** [comment]
> Hey, just checked the portal and looks like it has been fixed. Can I close this? @AviaOne

Great news, thank you
Yes please close this topic

**Comment by VictorTrustyDev** [comment]
Hello @AviaOne 
The Status is fetch from on-chain data, representing for Sequencer Operating Status and has 2 values:
| On-chain RollApp Sequencer Status | Web Displays |
| --- | --- |
| Proposer | Active Proposer |
| Inactive | Inactive |
I have no idea if it has any relation with the Portal Online/Offline information.
