### ISSUE TITLE
no ​​longer shows the correct values ​​for TVL or number of tokens

### ISSUE THREAD

**Issue by Aptosuper** [dymensionxyz/roller#568]
### Roller version

https://portal.dymension.xyz/rollapp/beerus_6243063-1

### OS

/

### Processor Architecture

/

### Steps to reproduce it

/

### Expected result

/

### Actual result

/

### Notes

My rollapp no ​​longer shows the correct values ​​for TVL or number of tokens.

I have made transfers of dym and BEE (my token) but nothing shows up.

https://portal.dymension.xyz/rollapp/beerus_6243063-1

**Comment by ItayLevyOfficial** [comment]
Opened on the portal dymensionxyz/portal#170
