### ISSUE TITLE
Error: error while starting settlement layer client: websocket: bad handshake

### ISSUE THREAD

**Issue by Huginntech** [dymensionxyz/roller#569]
Since the default Hub-RPC was down from time to time, I tried the RPC and API provided by other validators (I've tried it before) but I started getting a weird error and couldn't find a solution:

```
time="2023-10-25T06:57:33Z" level=info msg="starting node with ABCI dymint in-process[]"
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting multiAppConn service impl multiAppConn]" module=proxy
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=query module=abci-client
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=snapshot module=abci-client
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=mempool module=abci-client
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=consensus module=abci-client
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting EventBus service impl EventBus]" module=events
time="2023-10-25T06:57:33Z" level=info msg="service start[msg Starting PubSub service impl PubSub]" module=pubsub
badger 2023/10/25 06:57:33 INFO: All 4 tables opened in 4ms
badger 2023/10/25 06:57:33 INFO: Discard stats nextEmptySlot: 0
badger 2023/10/25 06:57:33 INFO: Set nextTxnTs to 6261
badger 2023/10/25 06:57:33 INFO: Deleting empty file: /root/.roller/rollapp/data/dymint/000013.vlog
time="2023-10-25T06:57:33Z" level=debug msg="Getting latest batch from settlement layer[]" module=settlement_client
time="2023-10-25T06:57:34Z" level=info msg="Updated latest height from settlement layer[latestHeight 3004]" module=settlement_client
time="2023-10-25T06:57:35Z" level=info msg="Updated sequencers list from settlement layer[sequencersList [0xc0030ffc98]]" module=settlement_client
time="2023-10-25T06:57:35Z" level=info msg="service start[msg Starting IndexerService service impl IndexerService]" module=txindex
time="2023-10-25T06:57:35Z" level=info msg="service start[msg Starting RPC service impl RPC]"
time="2023-10-25T06:57:35Z" level=debug msg="limiting number of connections[limit 900]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name health]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name genesis_chunked]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name tx]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name consensus_params]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name num_unconfirmed_txs]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name abci_query]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name status]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name block]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name validators]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name genesis]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name block_results]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name subscribe]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name blockchain]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name broadcast_tx_sync]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name unconfirmed_txs]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name broadcast_evidence]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name unsubscribe]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name net_info]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name block_by_hash]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name consensus_state]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name abci_info]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name unsubscribe_all]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name commit]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name check_tx]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name tx_search]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name block_search]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name dump_consensus_state]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name broadcast_tx_commit]"
time="2023-10-25T06:57:35Z" level=debug msg="registering method[name broadcast_tx_async]"
time="2023-10-25T06:57:35Z" level=debug msg="CORS enabled[origins [*] methods [HEAD GET POST] headers [Origin Accept Content-Type X-Requested-With X-Server-Time]]"
time="2023-10-25T06:57:35Z" level=info msg="service start[msg Starting Node service impl Node]"
time="2023-10-25T06:57:35Z" level=info msg="starting P2P client[]"
time="2023-10-25T06:57:35Z" level=debug msg="starting P2P client[]" module=p2p
time="2023-10-25T06:57:35Z" level=info msg="serving HTTP[listen address [::]:26657]"
time="2023-10-25T06:57:35Z" level=info msg="listening on[address /ip4/95.216.193.163/tcp/26656/p2p/12D3KooWQbejkygAUZpX5sECUUkHDSRLLSZvjZrpxRrzuh17oNpF]" module=p2p
time="2023-10-25T06:57:35Z" level=info msg="listening on[address /ip4/127.0.0.1/tcp/26656/p2p/12D3KooWQbejkygAUZpX5sECUUkHDSRLLSZvjZrpxRrzuh17oNpF]" module=p2p
time="2023-10-25T06:57:35Z" level=debug msg="setting up gossiping[]" module=p2p
time="2023-10-25T06:57:35Z" level=debug msg="setting up DHT[]" module=p2p
time="2023-10-25T06:57:35Z" level=info msg="no seed nodes - only listening for connections[]" module=p2p
time="2023-10-25T06:57:35Z" level=debug msg="setting up active peer discovery[]" module=p2p
time="2023-10-25T06:57:35Z" level=info msg="starting Celestia Data Availability Layer Client[]" module=celestia
time="2023-10-25T06:57:35Z" level=debug msg="settlement Layer Client starting.[]" module=settlement_client
time="2023-10-25T06:57:35Z" level=info msg="started state updates handler loop[]" module=settlement_client
Error: error while starting settlement layer client: websocket: bad handshake
Usage:
  rollapp-evm start [flags]
```
  
After changing the hub-rpc, I started experiencing this issue, but currently, no matter which endpoint I try, didn't work. 🤔

```
badger 2023/10/25 11:19:16 INFO: Set nextTxnTs to 28
badger 2023/10/25 11:19:16 INFO: Deleting empty file: /root/.roller/rollapp/data/dymint/000027.vlog
```

every auto restart these numbers are increasing.

Even though I moved my keys to a new server I continue to see the exact same error with new data.

**Comment by omritoptix** [comment]
Hey @Huginntech , thanks for the report!
The second log you've posted is actually not an issue but a regular partial log of the badger db.
Can you post the full log after changing the hub-rpc endpoint?

Also the silknodes endpoint should be stable and functioning currently.

**Comment by Huginntech** [comment]
You're welcome @omritoptix, unfortunately, I reset this server.

**Comment by nmluthfi** [comment]
Hello @omritoptix and @ItayLevyOfficial 

My roll app experiencing such error on Roller v1.0.3 with the default RPC..

Here's the log
`time="2023-12-22T12:08:11+01:00" level=info msg="starting node with ABCI dymint in-process[]"
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting multiAppConn service impl multiAppConn]" module=proxy
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=query module=abci-client
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=snapshot module=abci-client
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=mempool module=abci-client
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting localClient service impl localClient]" connection=consensus module=abci-client
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting EventBus service impl EventBus]" module=events
time="2023-12-22T12:08:11+01:00" level=info msg="service start[msg Starting PubSub service impl PubSub]" module=pubsub
badger 2023/12/22 12:08:11 INFO: All 47 tables opened in 30ms
badger 2023/12/22 12:08:11 INFO: Discard stats nextEmptySlot: 0
badger 2023/12/22 12:08:11 INFO: Set nextTxnTs to 10433
badger 2023/12/22 12:08:11 INFO: Deleting empty file: /root/.roller/rollapp/data/dymint/000078.vlog
2023/12/22 12:08:11 Connecting to wss://dymension-devnet.avail.tools/ws...
time="2023-12-22T12:08:12+01:00" level=debug msg="Getting latest batch from settlement layer[]" module=settlement_client
time="2023-12-22T12:08:13+01:00" level=info msg="Updated latest height from settlement layer[latestHeight 2314]" module=settlement_client
time="2023-12-22T12:08:13+01:00" level=info msg="Updated sequencers list from settlement layer[sequencersList [0xc0044f0660]]" module=settlement_client
time="2023-12-22T12:08:13+01:00" level=info msg="service start[msg Starting IndexerService service impl IndexerService]" module=txindex
time="2023-12-22T12:08:13+01:00" level=info msg="service start[msg Starting RPC service impl RPC]"
time="2023-12-22T12:08:13+01:00" level=debug msg="limiting number of connections[limit 900]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name unsubscribe_all]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name blockchain]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name genesis_chunked]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name block_results]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name consensus_state]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name abci_info]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name broadcast_evidence]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name net_info]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name check_tx]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name unconfirmed_txs]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name broadcast_tx_sync]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name broadcast_tx_async]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name abci_query]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name health]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name status]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name commit]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name unsubscribe]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name block_search]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name validators]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name subscribe]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name consensus_params]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name broadcast_tx_commit]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name block]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name block_by_hash]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name num_unconfirmed_txs]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name genesis]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name tx_search]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name dump_consensus_state]"
time="2023-12-22T12:08:13+01:00" level=debug msg="registering method[name tx]"
time="2023-12-22T12:08:13+01:00" level=debug msg="CORS enabled[origins [*] methods [HEAD GET POST] headers [Origin Accept Content-Type X-Requested-With X-Server-Time]]"
time="2023-12-22T12:08:13+01:00" level=info msg="service start[msg Starting Node service impl Node]"
time="2023-12-22T12:08:13+01:00" level=info msg="starting P2P client[]"
time="2023-12-22T12:08:13+01:00" level=debug msg="starting P2P client[]" module=p2p
time="2023-12-22T12:08:13+01:00" level=info msg="serving HTTP[listen address [::]:26657]"
time="2023-12-22T12:08:13+01:00" level=info msg="listening on[address /ip4/161.97.152.43/tcp/26656/p2p/12D3KooWPCA6bjAc4SFAK6dHirFnCvCbWcM85JkpY55PamVqKVvC]" module=p2p
time="2023-12-22T12:08:13+01:00" level=info msg="listening on[address /ip4/127.0.0.1/tcp/26656/p2p/12D3KooWPCA6bjAc4SFAK6dHirFnCvCbWcM85JkpY55PamVqKVvC]" module=p2p
time="2023-12-22T12:08:13+01:00" level=debug msg="setting up gossiping[]" module=p2p
time="2023-12-22T12:08:13+01:00" level=debug msg="setting up DHT[]" module=p2p
time="2023-12-22T12:08:13+01:00" level=info msg="no seed nodes - only listening for connections[]" module=p2p
time="2023-12-22T12:08:13+01:00" level=debug msg="setting up active peer discovery[]" module=p2p
time="2023-12-22T12:08:13+01:00" level=debug msg="settlement Layer Client starting.[]" module=settlement_client
time="2023-12-22T12:08:13+01:00" level=info msg="started state updates handler loop[]" module=settlement_client
time="2023-12-22T12:08:13+01:00" level=debug msg="trying to connect to peer[peer {12D3KooWPCA6bjAc4SFAK6dHirFnCvCbWcM85JkpY55PamVqKVvC: []}]" module=p2p
time="2023-12-22T12:08:13+01:00" level=error msg="failed to connect to peer[peer {12D3KooWPCA6bjAc4SFAK6dHirFnCvCbWcM85JkpY55PamVqKVvC: []} error failed to find peers: failed to find any peer in table]" module=p2p
Error: error while starting settlement layer client: websocket: bad handshake
Usage:`
