### ISSUE TITLE
About the roll-up deposit process

### ISSUE THREAD

**Issue by Tarbay** [dymensionxyz/roller#572]
### Roller version

roller version

### OS

os

### Processor Architecture

amd

### Steps to reproduce it

When I make a roll-up deposit, the notification windows showing that the transaction is completed remain open. We have to close it manually, wouldn't it be better if it closed automatically after a few seconds instead :) good work

### Expected result

When I make a roll-up deposit, the notification windows showing that the transaction is completed remain open. We have to close it manually, wouldn't it be better if it closed automatically after a few seconds instead :) good work

### Actual result

When I make a roll-up deposit, the notification windows showing that the transaction is completed remain open. We have to close it manually, wouldn't it be better if it closed automatically after a few seconds instead :) good work

**Comment by Tarbay** [comment]
When I make a roll-up deposit, the notification windows showing that the transaction is completed remain open. We have to close it manually, wouldn't it be better if it closed automatically after a few seconds instead :) good work #

**Comment by ItayLevyOfficial** [comment]
@ItzhakBokris

**Comment by ItayLevyOfficial** [comment]
Opened on the portal dymensionxyz/portal#169
