### ISSUE TITLE
dym rewards have stopped

### ISSUE THREAD

**Issue by Aptosuper** [dymensionxyz/roller#573]
### Roller version

v0.1.16-beta

### OS

/

### Processor Architecture

/

### Others

https://portal.dymension.xyz/rollapp/beerus_6243063-1

### Steps to reproduce it

/

### Expected result

/

### Actual result

/

### Relevant log output

```Shell
logs of the RollApp Sequencer :
time="2023-10-27T19:20:48Z" level=debug msg="ABCIQuery[path /ibc.core.channel.v1.Query/PacketCommitments height 3134]" module=events

logs of the IBC Relayer :
Failed to execute command: /usr/local/bin/roller_bins/rly, err: fork/exec /usr/local/bin/roller_bins/rly: no such file or directory
```

### Notes

no

**Comment by ItayLevyOfficial** [comment]
Hey! AFAIK this issue has been fixed. Can you confirm so I'll close it?

**Comment by Aptosuper** [comment]
Yep, you can close mate 👌 very good job team, thanks
