### ISSUE TITLE
[Feature Request]: Celesta endpoint config

### ISSUE THREAD

**Issue by JayLiu0580** [dymensionxyz/roller#580]
### Implementation ideas

Currently, the node configuration for Celestia is fixed in the code as static variables, such as:/data_ Layer/celestia/celestia.go.

```
const (
	CelestiaRestApiEndpoint = "https://api-arabica-9.consensus.celestia-arabica.com"
	DefaultCelestiaRPC      = "consensus-full-arabica-9.celestia-arabica.com"
	DefaultCelestiaNetwork  = "arabica"
)
```

With the upgrade of the Celestia testing network, the relevant configurations will no longer be valid. For example, the current version is  10, while the configuration in the roller code is still version 9, resulting in errors in building the RollerApp through the Roller.

I hope that the relevant configuration can be done in the form of a file (eg. celestia.toml), so that it can dynamically adapt to relevant changes.

**Comment by omritoptix** [comment]
Hi @JayLiu0580 . it's actually just the defaults. you can change it in `~/.roller/rollapp/config/dymint.toml`
