### ISSUE TITLE
Roller doesn't work with the rollapp template (non evm)

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#598]
Running roller with a non evm rollapp using the [rollapp template](https://github.com/dymensionxyz/rollapp) (version v0.1.0-rc5) returns the next error:

```
time="2023-11-11T16:10:15+01:00" level=debug msg="Submitting batch to DA layer[start height 1 end height 18 da height 71]" module=mock
time="2023-11-11T16:10:15+01:00" level=debug msg="Submitting batch to settlement layer[start height 1 end height 18]" module=settlement_client
panic: unable to unmarshal item.Data, err: Bytes left over in UnmarshalBinaryLengthPrefixed, should read 10 more bytes but have 178

goroutine 246 [running]:
github.com/dymensionxyz/dymint/settlement/dymension.(*HubClient).PostBatch(0x140001ee240, 0x140043e0a00, {0x102827720?, 0x1400463e0c0?}, 0x1200000000000000?)
	/Users/omridagan/go/1.19.10/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/settlement/dymension/dymension.go:207 +0xec4
github.com/dymensionxyz/dymint/settlement.(*BaseLayerClient).SubmitBatch(0x140018ca3c0, 0x140043e0a00, {0x102827720, 0x4}, 0x0?)
	/Users/omridagan/go/1.19.10/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/settlement/base.go:104 +0x188
github.com/dymensionxyz/dymint/block.(*Manager).submitNextBatch(0x140015dc2c0, {0x103bb2f38?, 0x1400011e018?})
	/Users/omridagan/go/1.19.10/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:794 +0x4ac
github.com/dymensionxyz/dymint/block.(*Manager).SubmitLoop(0x140015dc2c0, {0x103bb2f38, 0x1400011e018})
	/Users/omridagan/go/1.19.10/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:321 +0x250
created by github.com/dymensionxyz/dymint/block.(*Manager).Start
	/Users/omridagan/go/1.19.10/pkg/mod/github.com/dymensionxyz/dymint@v0.5.1-rc01/block/manager.go:186 +0x16c
```

I believe it's related to the fact that [rollapp template](https://github.com/dymensionxyz/rollapp) uses `cosmos.crypto.secp256k1.PubKey` and not `ethsecp` keys.

Running the rollapp template by itself works (without roller) so possibly has to do with how roller generates the rollapp key.

Could be related to latest change done on the [comsosclient](https://github.com/dymensionxyz/cosmosclient).

**Comment by ItayLevyOfficial** [comment]
Why v0.1.0-rc5? Looks like [v1.0.0-beta](https://github.com/dymensionxyz/rollapp/releases/tag/v1.0.0-beta) is newer.

**Comment by ItayLevyOfficial** [comment]
After checking, I can confirm that the error does not reproduce with [v1.0.0-beta](https://github.com/dymensionxyz/rollapp/releases/tag/v1.0.0-beta). This is because support for the new key type in dymint was added only in this release, not in v0.1.0-rc5. Please ask Johny to merge the updates from this version and try again.

**Comment by ItayLevyOfficial** [comment]
Created a new release [v0.1.0-rc6](https://github.com/dymensionxyz/rollapp/releases/tag/v0.1.0-rc6) with the upgraded dymint - can I close this issue? @omritoptix

**Comment by omritoptix** [comment]
yes. closing. thanks.
