### ISSUE TITLE
Deposit is not arriving to roll app

### ISSUE THREAD

**Issue by orkhanismayilov** [dymensionxyz/roller#605]
### Roller version

latest

### OS

Ubuntu 22.04.3 LTS

### Processor Architecture

x86_64

### Steps to reproduce it

I had issue with relayer and had run `roller relayer start --override` after that deposited funds do not arrive on roll app chain.

Before the result for `roller relayer status` was:
`Active src, channel-0 <-> channel-6049, dst`

After override it is:
`Active src, channel-1 <-> channel-7237, dst`

### Expected result

Deposited funds arrive on roll app chain.

### Actual result

Deposited funds do not arrive on roll app chain. Got this in tx_response:
```{"key":"packet_src_channel","value":"channel-6049"}, {"key":"packet_dst_channel","value":"channel-0"}```

However I did run `roller relayer start --override` command and now it is like:

`root@vmi1326194:~# roller relayer status
Active src, channel-1 <-> channel-7237, dst`

I suppose that is the issue for not receiving funds on roll app.

### Notes

Tx [link](https://explorer.silknodes.io/dymension/tx/A37A7800D915716D8E930A3124616CB4BFD723349E14914E5C08C8374ABE21C2) on explorer

**Comment by mtsitrin** [comment]
Try deposit again, it should use `channel-1` now

u deposit using `roller tx fund-faucet`?

**Comment by orkhanismayilov** [comment]
> Try deposit again, it should use `channel-1` now
> 
> u deposit using `roller tx fund-faucet`?

No I mean IBC Transfer via the "Deposit Funds" button on portal.
