### ISSUE TITLE
when i use the cmd "roller config export" the RPC field, REST field and EVM RPX field are Blank

### ISSUE THREAD

**Issue by theblackseaNFT** [dymensionxyz/roller#606]
### Roller version

Roller version v0.1.21-beta

### OS

ubuntu

### Processor Architecture

intel

### Steps to reproduce it

made the tutorial with no error message

### Expected result

rpc result

### Actual result

blank field

**Comment by ItayLevyOfficial** [comment]
This is the expected behavior, as roller can't know what your external RPC endpoints are. Which value at those fields would make more sense for you?
