### ISSUE TITLE
Running tests fails if roller binaries are not installed 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#615]
Following the readme.md doesn't work with running tests. 
```
=== RUN   TestInitCmd/Roller_config_init_with_default_values
/var/folders/gs/nlc8t34s4_7g94b61hckhrfm0000gn/T/test3177507433/.roller Roller config init with default values
💈 command execution failed: exit status 127, stderr: goenv: 'rollapp_evm' command not found
```

**Comment by ItayLevyOfficial** [comment]
Why? The [readme says](https://github.com/dymensionxyz/roller/blob/ff3983abe7acb4912323c7fefba126bb9c3f9cf6/README.md?plain=1#L17) you should first install the binaries. Do you want to make it more bold, and add this line also in the testing section?
