### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by onrkrr** [dymensionxyz/roller#618]
### Implementation ideas

0x71e12bc2ba2a7d7754ef1c007c1bea62ad0fb48b
I get this error when doing "undelegate". Why could it be?
![image](https://github.com/dymensionxyz/roller/assets/105444890/c15a04f0-66e4-4c9f-acbc-d287b8bc49f1)

**Comment by mtsitrin** [comment]
the error is descriptive.
seems u have ongoing undelegate requests.
undelegate process takes time for the funds to be unbonded

**Comment by onrkrr** [comment]
hımm ok, thanks..
________________________________
Gönderen: Michael Tsitrin ***@***.***>
Gönderildi: 10 Aralık 2023 Pazar 07:57
Kime: dymensionxyz/roller ***@***.***>
Bilgi: 10R ***@***.***>; Author ***@***.***>
Konu: Re: [dymensionxyz/roller] [Feature Request]: (Issue #618)


Closed #618<https://github.com/dymensionxyz/roller/issues/618> as not planned.
