### ISSUE TITLE
Error swallowed if create-sequencer command fails

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#623]
If create-sequencer command returns a response but the response is with `code` !=0 (which means the command failed), the roller ui still shows success.

example response that should fail but passes:

`{"height":"0","txhash":"1022C395A918BF93979FCF5D6DB8F0554AE14AB1F89A4D8E4915636CA21F678B","codespace":"sdk","code":13,"data":"","raw_log":"no fees provided: insufficient fee","logs":[],"info":"","gas_wanted":"200000","gas_used":"2042","tx":null,"timestamp":"","events":[]}`

**Comment by artemijspavlovs** [comment]
fixed in #831
