### ISSUE TITLE
roller tx register - errUnknownField "*types.MsgCreateRollapp": {TagNum: 8, WireType:"bytes"}: tx parse error

### ISSUE THREAD

**Issue by Love4crypto** [dymensionxyz/roller#630]
### Roller version

1.0.0-beta

### OS

Ubuntu 22.04

### Processor Architecture

x86_64

### Steps to reproduce it

![uknown-field](https://github.com/dymensionxyz/roller/assets/94926764/92f40877-ce24-403d-8b91-058bede09f3a)

### Expected result

It's expected that it register rollup

### Actual result

It throws an error

**Comment by mygithublogin** [comment]
I have the same problem now.

**Comment by omritoptix** [comment]
can you please try install the latest version of roller and try again

**Comment by omritoptix** [comment]
closing for now. feel free to open.
