### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by afsinkoroglu** [dymensionxyz/roller#632]
### Roller version

.

### OS

.

### Processor Architecture

.

### Others

I cannot do anything in the dimension application. The same warning appears.'Dymension Froopyland RPC client was unable to broadcast the transaction, please try again later.'

### Steps to reproduce it

'Dymension Froopyland RPC client was unable to broadcast the transaction, please try again later'

### Expected result

.

### Actual result

.

**Comment by omritoptix** [comment]
We had a halt chain during the upgrade. Should be ok now. Closing this.
