### ISSUE TITLE
Submitted worng address.

### ISSUE THREAD

**Issue by Alexmartal** [dymensionxyz/roller#650]
Hi Team,

My celestia address is celestia1klaf39jnnu6k35zrlaxnpyje706us4sfjwek3a ,

I have accidentally submitted an incorrect address which don't belongs to me.

I would like to request you kindly rest the data for the following address above.

Thanking you.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
