### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by kimchiii0319** [dymensionxyz/roller#651]
I have staked ATOM , TIA , OSMO well before december 19th (US time) but I am still not eligible. May I know why?
Or will I be eligible for the second airdrop? I staked at December 19 PH time which was Decembe 18 US time.
![Screenshot_20240103_021451_Leap Wallet](https://github.com/dymensionxyz/roller/assets/150874618/33d2d468-a6f3-4ec3-adb1-16bfceb67b2f)
![Screenshot_20240103_021459_Leap Wallet](https://github.com/dymensionxyz/roller/assets/150874618/25520987-fff6-4a5a-9eeb-f920e46a0338)
![Screenshot_20240103_021512_Leap Wallet](https://github.com/dymensionxyz/roller/assets/150874618/cb5ad0b9-1d57-417d-a5c4-8dd04793f2fa)

**Comment by kimchiii0319** [comment]
Screenshot was based on PH time which is December 18 US time.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
