### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Nowiki72** [dymensionxyz/roller#652]
### Implementation ideas

Hello Everyone

When making the claim and asking for an Eth address, I entered the one given to me by this page connecting my Kepler: https://portal.dymension.xyz/rollappsThis portal is for testing and will I lose the claimed DYM or will they appear there in the future?
Thank you all

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
