### ISSUE TITLE
Missing L2 claim despite lots of activity

### ISSUE THREAD

**Issue by StayCoolDK** [dymensionxyz/roller#654]
### Roller version

1

### OS

Windows

### Processor Architecture

x86

### Steps to reproduce it

 ✅  +900 transactions on ethereum mainnet 
 ✅  +300 transactions on arbitrum 
 ✅  transacted on optimism 
 ✅  transacted on base 
 ✅  received $ARB airdrop 
 ✅  received $OP airdrop 

### Expected result

I expected to be able to claim tokens.

### Actual result

No token claim

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
