### ISSUE TITLE
Trouble initializing relayer using the "roller run"

### ISSUE THREAD

**Issue by 0xcracka** [dymensionxyz/roller#658]
### Roller version

 Roller version v1.0.3-beta

### OS

aws linux

### Processor Architecture

 amd64

### Others

 Roller version v1.0.3-beta
💈 Build time: 2023-12-17T22:24:08+0000"
💈 Git commit: b60d9e1bfa5ee70a8e8cd0d4dd7126c06884be9c

### Steps to reproduce it

after funding addresses

running the roller, 
trouble with relayer initialization. 

### Expected result

want to fund faucet for next steps in deploying IBC bridge

### Actual result

stuck at starting...

**Comment by kellybasil185** [comment]
have you sorted it out because i'm literally facing same issue

**Comment by 0xcracka** [comment]
Nah I haven't....

**Comment by 0xcracka** [comment]
Global Flags:
      --log_format string   The logging format (json|plain) (default "plain")

time="2024-01-05T22:31:10Z" level=info msg="starting node with ABCI dymint in-process[]"
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting multiAppConn service impl multiAppConn]" module=proxy
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=query module=abci-client
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=snapshot module=abci-client
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=mempool module=abci-client
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting localClient service impl localClient]" connection=consensus module=abci-client
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting EventBus service impl EventBus]" module=events
time="2024-01-05T22:31:10Z" level=info msg="service start[msg Starting PubSub service impl PubSub]" module=pubsub
badger 2024/01/05 22:31:10 INFO: All 0 tables opened in 0s
badger 2024/01/05 22:31:10 INFO: Discard stats nextEmptySlot: 0
badger 2024/01/05 22:31:10 INFO: Set nextTxnTs to 0
badger 2024/01/05 22:31:10 INFO: Deleting empty file: /home/ec2-user/.roller/rollapp/data/dymint/000263.vlog
[ec2-user@ip-172-31-36-146 ~]$

**Comment by artemijspavlovs** [comment]
closing, old, running relayer was refactored in an upcoming version
