### ISSUE TITLE
Can't start relayer

### ISSUE THREAD

**Issue by Flyingtothemoon123** [dymensionxyz/roller#660]
The roller can't start and logs an error - can't find the relayer-rollap-key
I have checked that the key is located in the relayer>keys folder, and still getting an issue.

2024/01/08 17:31:49 Fetching service data...
2024/01/08 17:31:49 starting service command /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log
2024/01/08 17:31:49 process /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log exited, restarting...
2024/01/08 17:31:54 starting service command /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log
2024/01/08 17:31:54 process /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log exited, restarting...
2024/01/08 17:31:59 starting service command /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log
2024/01/08 17:31:59 process /root/rollapp_evm start --home /root/.roller/rollapp --log-file /root/.roller/rollapp/rollapp.log exited, restarting...
2024/01/08 17:32:00 command execution failed: exit status 1, stderr: Error: a key with name relayer-rollapp-key doesn't exist

![Screenshot 2024-01-08 183820](https://github.com/dymensionxyz/roller/assets/102158686/d4c04a26-c84a-42e3-a414-28715225b442)

**Comment by artemijspavlovs** [comment]
closing, old.
