### ISSUE TITLE
Metamask swapping — Could not integrate with Metamask on hub 

### ISSUE THREAD

**Issue by Traicye** [dymensionxyz/roller#664]
### Roller version

roller version 

### OS

iOS 17

### Processor Architecture

uname 

### Steps to reproduce it

Opening the portal. Requesting faucet tokens. Going to the hub page and using the swap feature. Tried swapping $dym tokens on the portal’s hub more than 3 times. 

### Expected result

It was expected that swapping the $dym token on the portal hub when using your Metamask wallet goes smoothly. 

That means that $dym tokens get swapped to tokens on the available list such as $ACE, etc. 

That didn’t happen. Instead the hub couldn’t integrate with Metamask. 

### Actual result

I got an error message saying that the hub wasn’t integrated with Metamask. 

### Notes

I think the community should look into why such error message is gotten when trying to use the swap feature using Metamask. 
![IMG_5846](https://github.com/dymensionxyz/roller/assets/82662228/ccf6d68e-a277-4c3f-8ec0-af5bb345a8b1)

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller, old.
