### ISSUE TITLE
[Feature Request]: Roll ape registration review

### ISSUE THREAD

**Issue by Booginator123** [dymensionxyz/roller#666]
### Implementation ideas

![Screenshot_20240111_210002_Discord](https://github.com/dymensionxyz/roller/assets/140609050/fc2e2738-6e45-42ff-bdf9-8044b979f09a)
I registered for roll ape role long before the registration ended, the bot crashed and I haven't gotten my role and your moderators are just telling me to move on. What's all this please? I thought posting early in the registering channel was all I needed to do. Now I am hearing I want lucky the fuck is that.

**Comment by cryptobdltd** [comment]
I registered for roll ape role yesterday  the registration ended today, and I haven't gotten my role....

my dym test evm address is     0xC7361A4b87Ca5354f7EB70c6EE2c671e9378053d

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller, old.
