### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by AykutMust** [dymensionxyz/roller#667]
### Implementation ideas

I have been participating in tesnets for the last year. I am someone who examines and researches tesnets every day. I recorded the name DYMENSION, but it slipped my mind. I just got into your test. I would be happy if you could give me the role of Roll Ape.

**Comment by cryptobdltd** [comment]
I registered for roll ape role yesterday the registration ended today, and I haven't gotten my role....

my dym test evm address is 0xC7361A4b87Ca5354f7EB70c6EE2c671e9378053d

**Comment by santosdios** [comment]
sorry the testnet is over there is no longer any point in assigning these roles.
