### ISSUE TITLE
Wrong airdrop adress

### ISSUE THREAD

**Issue by fudi966** [dymensionxyz/roller#668]
Hello!  I made a mistake during the DYM airdrop! Unfortunately, I put my METAMASK adress insted of my 
DYM 0x adress .Is there a solution to change my receipt address???

This is my cosmos adress: cosmos13wfgzvadutngaeg2kvuxkgukarrc53pgulf5p3
This is my osmo adress: osmo13wfgzvadutngaeg2kvuxkgukarrc53pg5y6yhr

My correct DYM adress for claim air drop is 0xeb2214631ee33c949bd1ecdd4d8a7f9ec9aaf8d9

**Comment by santosdios** [comment]
sorry but airdrop is already distributed, there is nothing that can be done at this point, continue to Discord for more information.
