### ISSUE TITLE
IBC tab cache issue (Web Browser)

### ISSUE THREAD

**Issue by yunusnode** [dymensionxyz/roller#669]
### Roller version

RollApp Fam and Ape

### OS

Macos

### Processor Architecture

Apple Silicon

### Steps to reproduce it

<img width="1470" alt="Ekran Resmi 2024-01-15 21 24 35" src="https://github.com/dymensionxyz/roller/assets/83891021/d6185351-f1cc-4632-926b-819ef31923ba">

As you can see in the picture, the IBC tab cannot be transferred because the balances cannot be loaded.

### Expected result

I think the problem of not loading the balance may be due to a cache problem.

### Actual result

This is a problem I have every day, I was going to bring it up earlier but I thought it might be a temporary problem. The problem is as follows:

I am trying to generate tx using the IBC tab from the daily portal site. Every day, before starting these operations, I can start the operations by deleting the cache from this page "https://portal.dymension.xyz/ibc". This is a big problem. Not every user can attribute the IBC page not working to the cache. The problem with the IBC page: balances cannot be loaded. When I clear the cache the problem is fixed. I think fixing this problem will be important for the development of the project.

Good work.

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller, old.
