### ISSUE TITLE
My computer is being blocked by Cloudfare from accessing the genesis.dymension.xyz site, even with a VPN on. Cloudflare Ray ID: 8471e7f5fb0e45f0

### ISSUE THREAD

**Issue by randman58** [dymensionxyz/roller#677]
My computer is being blocked from accessing the genesis.dymension.xyz site. I'm attempting check my eligibility for numerous times sensitive airdrops after receiving notices from Stakecito, one of my selected staking validators. Tried with VPN off and VPN on. Same result. 

Please advise. 
RandyM
![Screenshot (24857)](https://github.com/dymensionxyz/roller/assets/134007862/be66db96-2873-4271-97a0-2976e7395f3c)

Screen shot attached.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed, there is nothing that can be done at this point, continue to Discord for more information.
