### ISSUE TITLE
Dymension airdrop

### ISSUE THREAD

**Issue by JayKOT7** [dymensionxyz/roller#680]
Hi, I am not sure did I put my metamask address correctly to obtain $DYM, can I check it somewhere? 
osmo: osmo1xun3ra7kctekdqnhw6t5jjsp9204eku4zg72er
cosmos: cosmos1xun3ra7kctekdqnhw6t5jjsp9204eku42nd603
metamask: 0xA50B00B481177C163f10229AC8B44Eb43173979F

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
