### ISSUE TITLE
AVAIL Goldberg testnet coins are running out too fast

### ISSUE THREAD

**Issue by opsmanager1** [dymensionxyz/roller#683]
### Roller version

1.0.6

### OS

ubuntu 20.04

### Processor Architecture

intel core i5

### Others

After requesting tokens, rollapp works for about 6-7 hours and stops and asks for AVAIL tokens again
![IMG_8324](https://github.com/dymensionxyz/roller/assets/135651866/1070623d-dc5e-4ba2-b0df-61c8163714e2)
![5f2c61d7397ee359](https://github.com/dymensionxyz/roller/assets/135651866/09f09b02-756e-4ed3-8c9a-a33fd67bba1d)
watching the explorer, my coins are running out too fast
![f91c412a99ec06d6](https://github.com/dymensionxyz/roller/assets/135651866/a2148d6a-cc36-46f0-a066-4ece715bf02b)
    **15 min - 0.3001 AVL!!!!** but faucet get only 1 avail coin

### Steps to reproduce it

restart roller
restart VPS
get more coins from faucet

### Expected result

problem not solved

### Actual result

problem not solved

**Comment by Alping0** [comment]
Yes it consumes so fast, agree with you on that.

**Comment by opsmanager1** [comment]
Still have this issue

**Comment by santosdios** [comment]
sorry, the testnet has ended and the Avail task has ended, so we are closing support for this issue.
