### ISSUE TITLE
Using avail as DA client, I'm stuck in here for hours, what should i do?

### ISSUE THREAD

**Issue by talentbuilder** [dymensionxyz/roller#684]
<img width="1303" alt="image" src="https://github.com/dymensionxyz/roller/assets/10881940/8a8cb7ae-949e-446c-ba93-8e515364cbd0">

please help, I'm stuck in here for hours

**Comment by talentbuilder** [comment]
solved

**Comment by daningyn** [comment]
> solved

please tell what you did for solving this, I stuck here for hours too
