### ISSUE TITLE
[Feature Request]:Dymension rollapp failed to start service after deployment

### ISSUE THREAD

**Issue by tktketh** [dymensionxyz/roller#686]
### Implementation ideas

Dymension rollapp failed to start service after deployment.
DA layer is Avail.
![avail-da](https://github.com/dymensionxyz/roller/assets/103977379/315a3dde-4a9d-41f8-ad83-f083be45c84a)

**Comment by artemijspavlovs** [comment]
closing, old.

please re-open if still relevant
