### ISSUE TITLE
AVAIL relayer failing

### ISSUE THREAD

**Issue by RomeosWorld** [dymensionxyz/roller#687]
### Roller version

1.0.6-beta

### OS

Ubuntu 20.04.6 LTS

### Processor Architecture

x86_64

### Steps to reproduce it

After deployment 
use
sudo systemctl enable relayer
then
sudo systemctl start relayer
then
sudo systemctl status relayer

### Expected result

![image](https://github.com/dymensionxyz/roller/assets/90410487/5b26490f-ed4e-4fb8-91ba-e34b87e701a2)

### Actual result

● relayer.service - Roller relayer service
     Loaded: loaded (/etc/systemd/system/relayer.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2024-01-25 14:45:07 CET; 2s ago
    Process: 2217 ExecStart=/usr/local/bin/roller relayer start (code=exited, status=1/FAILURE)
   Main PID: 2217 (code=exited, status=1/FAILURE)

**Comment by santosdios** [comment]
sorry, the testnet has ended and the Avail task has ended, so we are closing support for this issue.
