### ISSUE TITLE
AVAIL RELAYER FAILED

### ISSUE THREAD

**Issue by demoso** [dymensionxyz/roller#688]
### Roller version

v1.0.6-beta

### OS

NAME="CentOS Stream" VERSION="9" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="9" PLATFORM_ID="platform:el9" PRETTY_NAME="CentOS Stream 9" ANSI_COLOR="0;31" LOGO="fedora-logo-icon" CPE_NAME="cpe:/o:centos:centos:9" HOME_URL="https://centos.org/" BUG_REPORT_URL="https://bugzilla.redhat.com/" REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9" REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

### Processor Architecture

NAME="CentOS Stream" VERSION="9"

### Steps to reproduce it

 tail -100f /root/.roller/rollapp/rollapp.log

### Expected result

....

### Actual result

![image](https://github.com/dymensionxyz/roller/assets/29779275/479dfe8a-8e38-43d6-b735-04ab97b4db2c)
![image](https://github.com/dymensionxyz/roller/assets/29779275/fe2f844d-c89c-4b10-8758-8dd7b481b0cf)

**Comment by demoso** [comment]
<img width="1404" alt="image" src="https://github.com/dymensionxyz/roller/assets/29779275/2a5db204-9da9-4965-a5be-32aebe8dd151">

**Comment by santosdios** [comment]
sorry the testnet is over there is no longer any point insorry, the testnet has ended and the Avail task has ended, so we are closing support for this issue. assigning these roles.
