### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by Olhanew** [dymensionxyz/roller#690]
### Roller version

Airdrop

### OS

Airdrop

### Processor Architecture

Airdrop

### Others

Hi. I was eligable for airdrop and claimed tokens. but now I see 0. Please explain what has changed, because it doesn’t look nice or fair.  cosmos1ulljhre30udyf3wz4w5sxrh9g5ltt6lfk6xvy3   osmo1ulljhre30udyf3wz4w5sxrh9g5ltt6lf7p4ujr

### Steps to reproduce it

Hi. I was eligable for airdrop and claimed tokens. but now I see 0. Please explain what has changed, because it doesn’t look nice or fair.  cosmos1ulljhre30udyf3wz4w5sxrh9g5ltt6lfk6xvy3   osmo1ulljhre30udyf3wz4w5sxrh9g5ltt6lf7p4ujr

### Expected result

Hi. I was eligable for airdrop and claimed tokens. but now I see 0. Please explain what has changed, because it doesn’t look nice or fair.  cosmos1ulljhre30udyf3wz4w5sxrh9g5ltt6lfk6xvy3   osmo1ulljhre30udyf3wz4w5sxrh9g5ltt6lf7p4ujr

### Actual result

Hi. I was eligable for airdrop and claimed tokens. but now I see 0. Please explain what has changed, because it doesn’t look nice or fair.  cosmos1ulljhre30udyf3wz4w5sxrh9g5ltt6lfk6xvy3   osmo1ulljhre30udyf3wz4w5sxrh9g5ltt6lf7p4ujr

### Relevant log output

```Shell
Hi. I was eligable for airdrop and claimed tokens. but now I see 0. Please explain what has changed, because it doesn’t look nice or fair.  cosmos1ulljhre30udyf3wz4w5sxrh9g5ltt6lfk6xvy3   osmo1ulljhre30udyf3wz4w5sxrh9g5ltt6lf7p4ujr
```

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
