### ISSUE TITLE
My testnet wallet was hacked. can I change my wallet address?

### ISSUE THREAD

**Issue by GamingPallab** [dymensionxyz/roller#691]
Sir, I got allocation on my testnet performed address 0x73543AeFcc6035b64d9c9CC6c18F2E2dc16A14A5.

It's eth chain was hacked. So, for security purpose I want to change my wallet address. Please help.
![1](https://github.com/dymensionxyz/roller/assets/157979694/72194314-e04e-4519-8382-51ae65032f00)
![2](https://github.com/dymensionxyz/roller/assets/157979694/f9448f14-206d-4fc2-a6ca-4f9c51e76053)

**Comment by GamingPallab** [comment]
My testnet performed connected discord id: anniecypher (Anniecypher#0717)

**Comment by GamingPallab** [comment]
Still no support team available.

**Comment by santosdios** [comment]
unfortunately it is not possible to perform this action, we proceed to close the incident.

**Comment by Kellyhact** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha
