### ISSUE TITLE
Aidrop DYM 

### ISSUE THREAD

**Issue by Stanley007777** [dymensionxyz/roller#693]
### Roller version

TIA

### OS

nie wiem

### Processor Architecture

nie wiem

### Others

nie wiem

### Steps to reproduce it

https://geteligibleuserrequest-xqbg2swtrq-uc.a.run.app/?address=celestia10p2jz9f8mqq3xsasq6jt3eg592mt6jl8zpx0sg

Wcześniej nie clajmowałem MM tylko podałem adres TIA i zakwalifikowałem i tyle, jak się pojawił zrzut to nie zakwalifikowałem dlatego ze u Kelpr wallet jest inny EVM i nie wiem jak usunąć i wprowadzić EVM  i odzyskać DYM.

### Expected result

Po prostu żebym mógł wiedzieć jak wprowadzić mój adres EVM zakwalifikowany do wallet Kelpr i usunąć EVM.

### Actual result

nie wiem.

### Relevant log output

```Shell
nie wiem
```

### Notes

to tyle.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
