### ISSUE TITLE
DYM allocation

### ISSUE THREAD

**Issue by ArienReeberg** [dymensionxyz/roller#695]
Dymension only checked my cosmos address and not the other chains. the accumulated amount is not accurate. 
my cosmos address is cosmos1ej9glu39r24qfmml4hzjnv4n47rz3enn089ml6
and EVM address is 0xFf935E24d108e316484D07bbd9D7d6469677C23e

please help

**Comment by santosdios** [comment]
it seems that your address has a balance so we are closing the incident.
