### ISSUE TITLE
I was ineligible even with the fact that I was active and I did all the necessary activities 

### ISSUE THREAD

**Issue by Oluwatammie** [dymensionxyz/roller#698]
![Screenshot_2024-02-02-08-20-15-696_com discord](https://github.com/dymensionxyz/roller/assets/106963536/ac9e3442-c550-42c2-a908-a20b9a6d8b03)

I registered way before the rollape role was closed and I don't know why the role was removed..
I interacted deeply with the ecosystem and I would be greatful is this issue is being checked out 

0xa4089f30e359e34fb3be2a1099c4c7b2dbcbef3d

**Comment by santosdios** [comment]
sorry, without the roll ape we have no way to check the veracity, it could be that you left discord and came back to the community for example... therefore I consider the incident closed.
