### ISSUE TITLE
Now what will happen to those testers who have not been able to submit the address, did their hard work go in vain?[Feature Request]: 

### ISSUE THREAD

**Issue by MrBankariya** [dymensionxyz/roller#699]
### Implementation ideas

Now what will happen to those testers who have not been able to submit the address, did their hard work go in vain?

0xabE6a21691065dc74F93E3391884528154950392

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
