### ISSUE TITLE
i did submit ETH Phatom wallet  what to do

### ISSUE THREAD

**Issue by solbigboss** [dymensionxyz/roller#700]
### Roller version

v1

### OS

windows

### Processor Architecture

reffis seddik

### Others

can you transefer it

### Steps to reproduce it

non

### Expected result

transfer it to meta mask wallet 

### Actual result

from you

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
