### ISSUE TITLE
roller config init --interactive does not work!

### ISSUE THREAD

**Issue by EAG-es** [dymensionxyz/roller#704]
### Roller version

💈 Roller version v1.0.6-beta 💈 Build time: 2024-01-18T09:05:45+0000" 💈 Git commit: 21b1b22e96466cc83b051ebacfb513b3a0d99de1

### OS

Linux Mint

### Processor Architecture

AMD64

### Steps to reproduce it

Following the instructions of: [https://docs.dymension.xyz/build/quick-start/roller-quick/initialize](https://docs.dymension.xyz/build/quick-start/roller-quick/initialize) I cannot get to work: dymd start
Roller
URL: https://docs.dymension.xyz/build/roller 
Install:
curl -L https://dymensionxyz.github.io/roller/install.sh | bash 
Initialize
roller config init --interactive
Address funding
Local Hub
- Local: Local development environment including option for Mock DA (not requiring tokens). Requires running a localhost Dymension Hub full node, please visit [here](https://docs.dymension.xyz/validate/dymension-hub/build-dymd?network=localhost) to run a localhost node.
Build Dymension is not necessary
git clone https://github.com/dymensionxyz/dymension.git
cd dymension
Install Go (https://go.dev/doc/install)
Remove any previous Go installation by deleting the /usr/local/go folder (if it exists), then extract the archive you just downloaded into /usr/local, creating a fresh Go tree in /usr/local/go:
sudo rm -rf /usr/local/go 
sudo tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
Add /usr/local/go/bin to the PATH environment variable. Editing ~/.profile file
 export PATH=$PATH:/usr/local/go/bin
Apply changes and check
source $HOME/.profile
go version
Install jq
sudo apt-get install jq
Build Dymension. This will install the dymd executable to your GOPATH environment variable (defaults is $HOME/go).
make install
EVM Rollup
emilio
Token: EMI
Mint for genesis: 1.000.000.000.000.000.000 (10^18)
Data layer: Local 

RollApp 'emilio_6633267-1' configuration files have been successfully generated on your local machine. Congratulations!

💰 Total Token Supply: 1,000,000,000,000,000,000 EMI. Note that 1 EMI == 1 * 10^18 uEMI (like 1 ETH == 1 * 10^18 wei).

🔑 Addresses:

  Sequencer, dymension_100-1 Hub | dym1pck06m5gajs399pun5uaugec2d30vnslm56fpt  
  Relayer, dymension_100-1 Hub   | dym1ydv8s0xlucx7rdpddsp02c4wt2s044gadx8ptf  

🔔 Please fund these addresses to register and run the rollapp.

To start the local Dymension hub, run:
dymd start
11:35AM INF Unlocking keyring
11:35AM INF starting ABCI with Tendermint
11:35AM INF starting node with ABCI Tendermint in-process
**11:35AM ERR failed init node error="couldn't read GenesisDoc file: open /home/emilio/.dymension/config/genesis.json: no such file or directory"
Error: couldn't read GenesisDoc file: open /home/emilio/.dymension/config/genesis.json: no such file or directory**
Fix error:
dymd init "local" --overwrite --chain-id "emilio_6334901-1"
dymd start
 
Give funds
dymd tx bank send local-user dym1pck06m5gajs399pun5uaugec2d30vnslm56fpt 1dym --gas-prices 100000000udym --yes -b block --keyring-backend test 
**Fails**

### Expected result

To work

### Actual result

Not working

-------------------------------------------------------------------------------------------------
### Next try: Roller (Local)
**roller config init --interactive**
Local Hub
ID: emilio
Token: EMI
Data layer: Local

Mint for genesis: 1.000.000.000.000.000.000 (10^18)

RollApp 'emilio_8239383-1' configuration files have been successfully generated on your local machine. Congratulations!

💰 Total Token Supply: 1,000,000,000,000,000,000 EMI. Note that 1 EMI == 1 * 10^18 uEMI (like 1 ETH == 1 * 10^18 wei).

🔑 Addresses:

 Sequencer, dymension_100-1 Hub | dym1gnmw3uf6ke3s8mvkha94k9zwy3dqzkkwv06m8p  
 Relayer, dymension_100-1 Hub   | dym1qnwutacrfa2mxyufy4839p80zzezm0dqhp0zgz  
 

🔔 Please fund these addresses to register and run the rollapp.

**dymd start**
**dymd tx bank send local-user dym1gnmw3uf6ke3s8mvkha94k9zwy3dqzkkwv06m8p 1dym --gas-prices 100000000uatom --yes -b block --keyring-backend test**
	…
_**raw_log: 'udym: invalid fee token'**_
timestamp: ""
tx: null
txhash: 08BE0E0DE3DC66B7BEEAE079BBC616E1DDEA0C42B21A34BA04708C9FC492B79D
dymd q bank balances dym1qg9yrr0dvcvwt507xm4pr9atsnylth8efz44ln
balances: []
Pagination:
next_key: null
total: "0"
roller tx register

### I cannot keep on

**Comment by artemijspavlovs** [comment]
hi,

appears you have `uatom` as the fee token in your second try, usually it's `adym` or `udym`, depending on the version you're running. try updating it and share whether that helps

**Comment by EAG-es** [comment]
> hi,
> 
> ```shell
> dymd tx bank send local-user \
> dym1gnmw3uf6ke3s8mvkha94k9zwy3dqzkkwv06m8p 1dym \
> --gas-prices **100000000uatom** --yes \
> -b block --keyring-backend test
> ```
> 
> appears you have `uatom` as the fee token in your second try, usually it's `adym` or `udym`, depending on the version you're running. try updating it and share whether that helps

I discovered that the error changed if I used "uatom"... But I just followed the instructions, and they do not work... And with "uatom" the error message changed... It said that the amount of "uatom" was not enough to pay fees (I changed the amount, and the amount required changed also. So I was not able to fund anything and I could not keep on the documentation) 
[URL: https://docs.dymension.xyz/build/roller ](URL: https://docs.dymension.xyz/build/roller )
`dymd tx bank send local-user $SEQUENCER_ADDR 1dym --gas-prices 100000000uatom --yes -b block --keyring-backend test`
code: 5
codespace: sdk
data: ""
events: []
gas_used: "21090"
gas_wanted: "200000"
height: "0"
info: ""
logs: []
**raw_log: '0uatom is smaller than 20000000000000uatom: insufficient funds: insufficient**
  funds'
timestamp: ""
tx: null
txhash: FA9691923DD6CE24DE716DAC14196664C80B6B51B7D19EFBF7881C0BB66240F9

`dymd tx bank send local-user $SEQUENCER_ADDR 1dym --gas-prices 20000000000000uatom --yes -b block --keyring-backend `test
code: 5
codespace: sdk
data: ""
events: []
gas_used: "21090"
gas_wanted: "200000"
height: "0"
info: ""
logs: []
**raw_log: '0uatom is smaller than 4000000000000000000uatom: insufficient funds: insufficient**
  funds'
timestamp: ""
tx: null
txhash: A1B717ACDFA97D48CB8EF0E811CF7651203069C1B201F9713D45314E6C25B43E
