### ISSUE TITLE
Review my participation in the project

### ISSUE THREAD

**Issue by laaouad2121** [dymensionxyz/roller#705]
I haven't received anything yet. Knowing that I was involved in the project from the beginning. I was banned from Discord for no reason
![ooooooo](https://github.com/dymensionxyz/roller/assets/129931163/0b3f0835-3083-4e97-a70c-02b66d04378f)
![ppppppppppppppppppppppppppppppppp](https://github.com/dymensionxyz/roller/assets/129931163/7be3f7ff-529a-4289-9068-7444c007c359)
![pppppppppppppppppppppppppppppppppppp](https://github.com/dymensionxyz/roller/assets/129931163/974a6a3e-ed26-4749-9039-4b09008ea915)
![ppppppppppppppppppppppppppppppppppppp](https://github.com/dymensionxyz/roller/assets/129931163/5772b0fc-749e-4408-b0e7-d8ea4e84807d)
![tttttt](https://github.com/dymensionxyz/roller/assets/129931163/635d9a4c-5d36-4500-9f05-f44e93f5766c)
![ùùùùùùùùùùùùùùùùùùùùùùùùùùùùùùùùùùù](https://github.com/dymensionxyz/roller/assets/129931163/9f867e71-0b9d-404d-b87b-5b80ae83fa1a)

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
