### ISSUE TITLE
Not getting my Dym 

### ISSUE THREAD

**Issue by slimani109** [dymensionxyz/roller#706]
I got qualified through the criteria of holding 1sol+ on snapshot and I submitted my evm now I couldn’t not see anything there
Here’s my solana wallet thst got qualified: HdwYhQcPxwWJebLGWDVLumamdWsdVqu73Zm2jeSHZ7Yk

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
