### ISSUE TITLE
In Froopyland: roller config init --interactive does not work!

### ISSUE THREAD

**Issue by EAG-es** [dymensionxyz/roller#707]
### Roller version

💈 Roller version v1.0.6-beta 💈 Build time: 2024-01-18T09:05:45+0000" 💈 Git commit: 21b1b22e96466cc83b051ebacfb513b3a0d99de1

### OS

Linux Mint

### Processor Architecture

AMD64

### Steps to reproduce it

URL: https://docs.dymension.xyz/build/roller 
**Install:**
curl -L https://dymensionxyz.github.io/roller/install.sh | bash 
**Initialize**
roller config init --interactive
**Address funding**
Froopyland 
**EVM Rollup**
Emilio
**Token:** EMI
Mint for genesis: 1.000.000.000.000.000.000 (10^18)
Data layer: Celestia (Avail, Local)

RollApp: emilio_3592720-1
Sequencer: dym1374w75zphks89gmyxfg4hhs0zh52tqjh23300d
Relayer: dym19tdamyszfl3h75f5642ew2356h0frt97t4ttda
DA, arabiga Network: celestia1amj3u0l0j2uuq6w8rl44xprv08qlhqwekww45
**Faucet (get funds). **
Go to discord channel: https://discord.com/channels/956961633165529098/1143231362468434022 
$request dym1374w75zphks89gmyxfg4hhs0zh52tqjh23300d
$request dym19tdamyszfl3h75f5642ew2356h0frt97t4ttda
Go to discord channel: https://discord.com/channels/956961633165529098/1128048548999610451 
$request celestia1amj3u0l0j2uuq6w8rl44xprv08qlhqwekww45e
Registering the RollApp adds a namespace in the Dymension Hub to account for the newly initalized RollApp.
roller tx register
💈 Rollapp 'emilio_3592720-1' has been successfully registered on the hub.
**To start the RollApp run the following command:**
roller run  

**NOTE: if your relayer stays in one of the states indefinitely:
Establishing IBC transfer channel**
💈 Creating clients…
💈 Updating clients…
💈 Creating connection…
💈 Creating channel…
💈 Waiting for channel completion….
💈 Creating channel…
Start the relayer again with:
roller relayer start --override 
**Fails**

### Expected result

Expected to work

### Actual result

![Captura de pantalla 2024-02-06 165612](https://github.com/dymensionxyz/roller/assets/34218003/5019bd35-f658-41c9-aac2-e2c1942f989c)

### Notes

I have tried Local... Now Froopyland... I see difficult to choose this technology unless get to know how to fix these problems...

**Comment by EAG-es** [comment]
> ### Roller version
> 💈 Roller version v1.0.6-beta 💈 Build time: 2024-01-18T09:05:45+0000" 💈 Git commit: [21b1b22](https://github.com/dymensionxyz/roller/commit/21b1b22e96466cc83b051ebacfb513b3a0d99de1)
> 
> ### OS
> Linux Mint
> 
> ### Processor Architecture
> AMD64
> 
> ### Others
> _No response_
> 
> ### Steps to reproduce it
> URL: https://docs.dymension.xyz/build/roller **Install:** curl -L https://dymensionxyz.github.io/roller/install.sh | bash **Initialize** roller config init --interactive **Address funding** Froopyland **EVM Rollup** Emilio **Token:** EMI Mint for genesis: 1.000.000.000.000.000.000 (10^18) Data layer: Celestia (Avail, Local)
> 
> RollApp: emilio_3592720-1 Sequencer: dym1374w75zphks89gmyxfg4hhs0zh52tqjh23300d Relayer: dym19tdamyszfl3h75f5642ew2356h0frt97t4ttda DA, arabiga Network: celestia1amj3u0l0j2uuq6w8rl44xprv08qlhqwekww45 **Faucet (get funds). ** Go to discord channel: https://discord.com/channels/956961633165529098/1143231362468434022 $request dym1374w75zphks89gmyxfg4hhs0zh52tqjh23300d $request dym19tdamyszfl3h75f5642ew2356h0frt97t4ttda Go to discord channel: https://discord.com/channels/956961633165529098/1128048548999610451 $request celestia1amj3u0l0j2uuq6w8rl44xprv08qlhqwekww45e Registering the RollApp adds a namespace in the Dymension Hub to account for the newly initalized RollApp. roller tx register 💈 Rollapp 'emilio_3592720-1' has been successfully registered on the hub. **To start the RollApp run the following command:** roller run
> 
> **NOTE: if your relayer stays in one of the states indefinitely: Establishing IBC transfer channel** 💈 Creating clients… 💈 Updating clients… 💈 Creating connection… 💈 Creating channel… 💈 Waiting for channel completion…. 💈 Creating channel… Start the relayer again with: roller relayer start --override **Fails**
> 
> ### Expected result
> Expected to work
> 
> ### Actual result
> ![Captura de pantalla 2024-02-06 165612](https://private-user-images.githubusercontent.com/34218003/302712921-5019bd35-f658-41c9-aac2-e2c1942f989c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTY5MzEsIm5iZiI6MTcwNzMxNjYzMSwicGF0aCI6Ii8zNDIxODAwMy8zMDI3MTI5MjEtNTAxOWJkMzUtZjY1OC00MWM5LWFhYzItZTJjMTk0MmY5ODljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE0MzcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNWJhMjU3ZjMxYTIyYzA1N2U4OGRjZWMxMjEwNzEyMmE1ODk2MjczYWM5YWFkOTQ2MWM3ZWJhMWRlYTQwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.npoKDp938lrmlKAhDsYRZPuPG9z9Ff1DOvBXy8WvCRE)
> 
> ### Relevant log output
> _No response_
> 
> ### Notes
> I have tried Local... Now Froopyland... I see difficult to choose this technology unless get to know how to fix these problems...

This morning I did: roller run
And it worked!
I do not know why did not work the fist time...
But still there are problems with: **Local**...

**Comment by santosdios** [comment]
please refer to the discord for this type of incidents, we proceed to close the issue here
