### ISSUE TITLE
Sir, My portal address that is connected is wrong but eligible this wrong address . What can i do now

### ISSUE THREAD

**Issue by kabirgbonline** [dymensionxyz/roller#709]
Sir i join this rollapp by 0x4A9C0b1C3a97603E2B03fdEBB3C24067E695abdB this. After connection i saw this 0x4f70be5b4c055be610846d310378cf64163b949e . But i do not know how this address generate. I am eligible by this  address 0x4f70be5b4c055be610846d310378cf64163b949e .How to solve this problem.

**Comment by kabirgbonline** [comment]
Sir, Please recover soon

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
