### ISSUE TITLE
I claimed DYM but can't see any 

### ISSUE THREAD

**Issue by Freedomfightersng** [dymensionxyz/roller#710]
### Implementation ideas

Hi, you guys are doing great.

I have a problem pls. I was eligible with my solana wallet (5aJBCkho5do8vZ3qFc2eTtvyJJXwdXgVu5qPDMaay4DN), claimed with my METAMASK (0x152280a1bcB35CB67981eCb3bF5De9ef48304143) and you gave me this DYM address (0x7987cf00451fbccb0ec514ac9f38b9eb7b7ad4c5).

Pls how do I claim the airdrop because my METAMASK is showing 0 DYM but I can still see the allocation in my assetdash dashboard.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
