### ISSUE TITLE
[Feature Request]: i send my dym token to another wallet but not received my tokens 

### ISSUE THREAD

**Issue by bandara2004** [dymensionxyz/roller#711]
### Implementation ideas

 i send my dym token to another wallet but not received my tokens .. sir why ??
 txn hash: 0xec8de4253b98cf54b0ff626f980cb4cd9b534d098b8892e38581a2fdeceec173
 
![Screenshot 2024-02-06 235800](https://github.com/dymensionxyz/roller/assets/131760783/2c15a78e-8c17-488b-ac50-503d37d77ac2)

**Comment by bandara2004** [comment]
![Uploading Screenshot 2024-02-07 005052.png…]()

**Comment by santosdios** [comment]
please refer to the discord for this type of incidents, we proceed to close the issue here
