### ISSUE TITLE
Dymension airdrop claim bug

### ISSUE THREAD

**Issue by Ragnaroking** [dymensionxyz/roller#712]
### Roller version

Latest/launch

### OS

No idea

### Processor Architecture

No idea

### Others

Dym that I could claim before and I have screenshoted is no longer eligible for my wallet. Many other people have this issue and have been posting about it in the discord. Why did my allocation disappear?
![Screenshot_20240202-220839](https://github.com/dymensionxyz/roller/assets/159182080/4f788051-09bf-4617-95d2-51950bcd3629)
![Screenshot_20240206-113128](https://github.com/dymensionxyz/roller/assets/159182080/4728c051-3e39-439d-8f5a-79fd56e4d3ab)
Wallet address: 0x75531CC36Fec81420225E77e76656F161f195b86

### Steps to reproduce it

Claim airdrop through genesis dymension.xyz

### Expected result

Claim airdrop
![Screenshot_20240202-220839](https://github.com/dymensionxyz/roller/assets/159182080/bdf3ebc7-22a0-4775-92b9-26d7b7e367b4)

### Actual result

Nothing to claim apparently 
![Screenshot_20240206-113128](https://github.com/dymensionxyz/roller/assets/159182080/c3f29265-0c3f-47bf-bd70-d0db8db71ad3)

### Relevant log output

```Shell
Website
```

### Notes

Why did my claim disappear?

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
