### ISSUE TITLE
IBC tansfert approved but not receive

### ISSUE THREAD

**Issue by victoriel34** [dymensionxyz/roller#713]
### Roller version

none

### OS

none

### Processor Architecture

none

### Others

https://dymension.explorers.guru/transaction/0E202C17DA8ECADE7BAE765C279B945659D561A01986B4B815DB193BCE0402A8

### Steps to reproduce it

https://dymension.explorers.guru/transaction/0E202C17DA8ECADE7BAE765C279B945659D561A01986B4B815DB193BCE0402A8

### Expected result

https://dymension.explorers.guru/transaction/0E202C17DA8ECADE7BAE765C279B945659D561A01986B4B815DB193BCE0402A8

### Actual result

https://osmosis.explorers.guru/account/osmo1k2nwtnxrtmh4q9mjsp360lvwse52v987dtmngr

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to transactions are usually reported and resolved on discord
