### ISSUE TITLE
Didnt get my DYM tokens for ATOM and TIA staking

### ISSUE THREAD

**Issue by twist72** [dymensionxyz/roller#715]
### Roller version

I am old crypto user and i got staking atom and tia tokens, and before i was operate in Optimistic roll-up

### OS

mac os

### Processor Architecture

uname

### Steps to reproduce it

=(

### Expected result

=(

### Actual result

=(

### Notes

![2024-02-06 21 25 33](https://github.com/dymensionxyz/roller/assets/159186275/56563883-c44b-4f85-8c14-210c4ad67e32)
![2024-02-06 21 25 40](https://github.com/dymensionxyz/roller/assets/159186275/2bac1d7d-f8a4-485f-9aba-d324b9add197)
![2024-02-06 21 25 45](https://github.com/dymensionxyz/roller/assets/159186275/6ab3e495-da1d-45ef-b674-d5286315b5b3)

**Comment by twist72** [comment]
celestia1sfwnhw0vj79hlh7qm5lgpp2hulvd3v07ah20ja
cosmos1sfwnhw0vj79hlh7qm5lgpp2hulvd3v07vamlgs
0x14018f7C4fCd3e827d6232d73136334ED33FfdD3

what i was doing wrong?

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
