### ISSUE TITLE
receved half airdrop

### ISSUE THREAD

**Issue by deejayvirg** [dymensionxyz/roller#718]
### Roller version

half airdrop received - 150 dym expected

### OS

half airdrop received

### Processor Architecture

0x6f982D235d41a4E6e0f6550eA0b8cd349d91B222

### Others

Hi,
I received only 75 dym,at the claim process it showed me 150 dym to claim.
Can you please tell me what's the problem?

### Steps to reproduce it

Hi,
I received only 75 dym,at the claim process it showed me 150 dym to claim.
Can you please tell me what's the problem?

### Expected result

Hi,
I received only 75 dym,at the claim process it showed me 150 dym to claim.
Can you please tell me what's the problem?

### Actual result

Please check my claim address 0x6f982D235d41a4E6e0f6550eA0b8cd349d91B222

### Relevant log output

```Shell
Hi,
I received only 75 dym,at the claim process it showed me 150 dym to claim.
Can you please tell me what's the problem?
```

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
