### ISSUE TITLE
Missing airdrop

### ISSUE THREAD

**Issue by mirito2806** [dymensionxyz/roller#721]
### Roller version

Dindt get my tokens

### OS

Token

### Processor Architecture

mirito

### Steps to reproduce it

Hello i claim my DYM tokens with evm adress, check again after the redistribution it increase the quantity but they are not in my wallet

### Expected result

expect to get tokens in this adress0x261a363c6C3f55FC93E2B3d113A3AEe73233694a

### Actual result

Dindt get any tokens...

### Notes

Im a atom staker cosmos1rj7pl8lhx8a5ftcsy93fvy6f2wvzpnnev22sln

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
