### ISSUE TITLE
Wallet help

### ISSUE THREAD

**Issue by CrytpoMartianX** [dymensionxyz/roller#723]
Hi all,  it's hard to find someone to actually assist, so i'll try here.  I don't recall what wallet i used to receive DYM.  i checked all my wallets i have and none have it.  it was only 78 i think, but would love to get that staked asap.  could anyone assist me with finding the wallet it went to?

This is the cosmos wallet that was eligible for it.

cosmos150n9yyjauuvgzhg0w6p7wku7847rc2vcqshv3u

i know you're all busy, but would be greatly appreciated.

**Comment by CrytpoMartianX** [comment]
I believe i used my phantom wallet like others in the discord, but it's not showing up for anyone using phantom.

**Comment by santosdios** [comment]
sorry but we don't have any information about which address you might have chosen, you will have to check it in your wallets. i'm closing the issue
