### ISSUE TITLE
Transfer from Cosmos to DYM spinning for 4 hours

### ISSUE THREAD

**Issue by NFTSSA** [dymensionxyz/roller#724]
### Roller version

Unknown

### OS

unknown

### Processor Architecture

Unknown

### Others

![image](https://github.com/dymensionxyz/roller/assets/98477862/c91fe96d-01be-4c8d-b670-fa956207cb61)

### Steps to reproduce it

I have done htis a number of times and it always errored out.  i do an ibc transfer from cosmos to DYM and have also tried to do an IBC transfer to osmos, both failed and the most recent one has been spinning for more than 4 hours.

### Expected result

Expected to receive in DYM wallet after IBC transfer

### Actual result

transaction spins or errors out.

**Comment by santosdios** [comment]
hey Have you resolved the issue?
