### ISSUE TITLE
MM can't connect to Dymension Portal

### ISSUE THREAD

**Issue by xtemc** [dymensionxyz/roller#725]
![image](https://github.com/dymensionxyz/roller/assets/159211672/23bb0868-133c-4dd2-91be-b0fc9642d107)

I have an issue where I can't seem to connect my MM to the dymension portal website? my MM is signed in but comes up with MM isn't installed when I press connect

**Comment by santosdios** [comment]
This is usually fixed by clearing the browser cache and refreshing the page... please continue to follow up on the Discord technical channel for better tracking.
