### ISSUE TITLE
AIRDROP NO RECEIVED IN MY WALLET METAMASK EVM

### ISSUE THREAD

**Issue by philmago** [dymensionxyz/roller#727]
### Implementation ideas

I was eligible for around 300 dym with my tia osmo and atom stacked on keplr but I received nothing on the EVM address that I had entered three times.
I don't understand why I haven't received anything.

**Comment by philmago** [comment]
my name in discord is neotrix
my adress atom : cosmos1hqm2lxevw7en8hzhq3wwsax52982h6nv2h2h30
TIA : celestia1hqm2lxevw7en8hzhq3wwsax52982h6nvmam8tz
Adress osmosis : osmo1hqm2lxevw7en8hzhq3wwsax52982h6nvzve88a

**Comment by santosdios** [comment]
sorry, the airdrop is already distributed and it seems that the process does not show any bugs so the team considers this topic closed as there is no evidence of an error in the process.
