### ISSUE TITLE
[Feature Request]: multicall2 contract

### ISSUE THREAD

**Issue by lhypj** [dymensionxyz/roller#728]
### Implementation ideas

Hello Dymension Team, I am an engineer from debank. We would like to deploy a contract on the EVM chain, but currently, we don't have the necessary permissions. Can you assist us in deploying a multicall2 contract(https://etherscan.io/address/0x5ba1e12693dc8f9c48aad8770482f4739beed696#code), or grant deployment permissions to our test address (0x5952f70fef1cbc26856d149646d4a8f97e923ee7)?

**Comment by alanwilhelm** [comment]
Devs are largely absent aren't they?

**Comment by artemijspavlovs** [comment]
you can deploy contracts to our public rolappx (evm) and rollapp y (wasm) rollapps

closing, this is not related to roller.
