### ISSUE TITLE
Dymension airdrop claims page

### ISSUE THREAD

**Issue by Adamuses** [dymensionxyz/roller#729]
### Implementation ideas

From the discord group, I realised that given the relatively short frame to claim the airdrops, many of us who are busy with life missed the deadlines did not managed to claim the airdrops in time, or there's error between actual claimed amount and supposed to claim amount. Can you set up a portal page for the community members to connect with their eligible wallets to further claim or verify the airdrops claims?

**Comment by santosdios** [comment]
the airdrop has already been distributed, and no new claims are possible at this stage.

**Comment by albanbo1** [comment]
Hello, I have won the airdrop. but my DYM hasnt come.
my eth addres   0x412790d5b6e1a84917a43d0d38b44ca267a84a45
dym1gynep4dkux5yj9ay85xn3dzv5fn6sjj97xganr
also my ceslta stake
addres is celestia1e27a8hycahqkym2ucdtecczu59t5av742qkrr7
I need thee tx hash so we can see why they didnt come

**Comment by santosdios** [comment]
yes, as you say you have your DYM, maybe you need help to access your wallet,.. please continue on Discord, you can close this thread and tag me if you need help:
mon.cumulo.pro
...

https://dym.fyi/address/0x412790d5b6e1a84917a43d0d38b44ca267a84a45

**Comment by albanbo1** [comment]
bro they never come in my wallet . When I claim i use binnace etherum
addres , and they never come
