### ISSUE TITLE
for the in your initial rpc

### ISSUE THREAD

**Issue by Wawanahayy** [dymensionxyz/roller#730]
### Roller version

initial

### OS

metamask

### Processor Architecture

metamask

### Others

send in your initial rpc
Network Name : Dymension
RPC URL : https://froopyland.dymension.xyz/29/gentes1_2_24/evmrpc
CHAIN ID : 1100
SYMBOL : DYM

### Steps to reproduce it

i add rpc send to my wallet TX pending and rpc down, TX interrupted, not recived my address los my balance

### Expected result

{2 items
"tx":{3 items
"body":{5 items
"messages":[1 item
0:{5 items
"@type":string"/ethermint.evm.v1.MsgEthereumTx"
"data":{...}10 items
"size":int0
"hash":string"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"
"from":string""
}
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{1 item
"@type":string"/ethermint.evm.v1.ExtensionOptionsEthereumTx"
}
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[1 item
0:{...}2 items
]
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"tx_response":{13 items
"height":string"74"
"txhash":string"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"
"codespace":string""
"code":int0
"data":string"12730A272F65746865726D696E742E65766D2E76312E4D7367457468657265756D5478526573706F6E736512480A423078363566616532653630653935643533643663376665376361376466613234333033353033613131343537646436386666366239393333366131353464326431332888A401"
"raw_log":string"[{"msg_index":0,"events":[{"type":"burn","attributes":[{"key":"burner","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1t5tkjqjq7vrgpumqhtyd2vm5gsmxrkerugcswt"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coinbase","attributes":[{"key":"minter","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"ethereum_tx","attributes":[{"key":"amount","value":"199997577320474753477"},{"key":"ethereumTxHash","value":"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"},{"key":"txIndex","value":"89"},{"key":"txGasUsed","value":"21000"},{"key":"txHash","value":"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"},{"key":"recipient","value":"0x5d17690240F30680F360bAc8d53374443661Db23"}]},{"type":"message","attributes":[{"key":"action","value":"/ethermint.evm.v1.MsgEthereumTx"},{"key":"sender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"sender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"module","value":"evm"},{"key":"sender","value":"0xCB59c1cfdc4199F19A209115c87A75592510Ed0E"},{"key":"txType","value":"0"}]},{"type":"transfer","attributes":[{"key":"recipient","v..."
"logs":[1 item
0:{3 items
"msg_index":int0
"log":string""
"events":8 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
}
]
"info":string""
"gas_wanted":string"21000"
"gas_used":string"21000"
"tx":{4 items
"@type":string"/cosmos.tx.v1beta1.Tx"
"body":{5 items
"messages":[1 item
0:{...}5 items
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{...}1 item
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[...]1 item
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"timestamp":string"2024-02-06T13:58:55Z"
"events":22 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
[8 - 10]
[10 - 12]
[12 - 14]
[14 - 16]
[16 - 18]
[18 - 20]
[20 - 22]
}
}

### Actual result

{2 items
"tx":{3 items
"body":{5 items
"messages":[1 item
0:{5 items
"@type":string"/ethermint.evm.v1.MsgEthereumTx"
"data":{...}10 items
"size":int0
"hash":string"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"
"from":string""
}
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{1 item
"@type":string"/ethermint.evm.v1.ExtensionOptionsEthereumTx"
}
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[1 item
0:{...}2 items
]
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"tx_response":{13 items
"height":string"74"
"txhash":string"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"
"codespace":string""
"code":int0
"data":string"12730A272F65746865726D696E742E65766D2E76312E4D7367457468657265756D5478526573706F6E736512480A423078363566616532653630653935643533643663376665376361376466613234333033353033613131343537646436386666366239393333366131353464326431332888A401"
"raw_log":string"[{"msg_index":0,"events":[{"type":"burn","attributes":[{"key":"burner","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1t5tkjqjq7vrgpumqhtyd2vm5gsmxrkerugcswt"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coinbase","attributes":[{"key":"minter","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"ethereum_tx","attributes":[{"key":"amount","value":"199997577320474753477"},{"key":"ethereumTxHash","value":"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"},{"key":"txIndex","value":"89"},{"key":"txGasUsed","value":"21000"},{"key":"txHash","value":"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"},{"key":"recipient","value":"0x5d17690240F30680F360bAc8d53374443661Db23"}]},{"type":"message","attributes":[{"key":"action","value":"/ethermint.evm.v1.MsgEthereumTx"},{"key":"sender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"sender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"module","value":"evm"},{"key":"sender","value":"0xCB59c1cfdc4199F19A209115c87A75592510Ed0E"},{"key":"txType","value":"0"}]},{"type":"transfer","attributes":[{"key":"recipient","v..."
"logs":[1 item
0:{3 items
"msg_index":int0
"log":string""
"events":8 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
}
]
"info":string""
"gas_wanted":string"21000"
"gas_used":string"21000"
"tx":{4 items
"@type":string"/cosmos.tx.v1beta1.Tx"
"body":{5 items
"messages":[1 item
0:{...}5 items
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{...}1 item
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[...]1 item
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"timestamp":string"2024-02-06T13:58:55Z"
"events":22 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
[8 - 10]
[10 - 12]
[12 - 14]
[14 - 16]
[16 - 18]
[18 - 20]
[20 - 22]
}
}

### Relevant log output

```Shell
{2 items
"tx":{3 items
"body":{5 items
"messages":[1 item
0:{5 items
"@type":string"/ethermint.evm.v1.MsgEthereumTx"
"data":{...}10 items
"size":int0
"hash":string"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"
"from":string""
}
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{1 item
"@type":string"/ethermint.evm.v1.ExtensionOptionsEthereumTx"
}
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[1 item
0:{...}2 items
]
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"tx_response":{13 items
"height":string"74"
"txhash":string"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"
"codespace":string""
"code":int0
"data":string"12730A272F65746865726D696E742E65766D2E76312E4D7367457468657265756D5478526573706F6E736512480A423078363566616532653630653935643533643663376665376361376466613234333033353033613131343537646436386666366239393333366131353464326431332888A401"
"raw_log":string"[{"msg_index":0,"events":[{"type":"burn","attributes":[{"key":"burner","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_received","attributes":[{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1t5tkjqjq7vrgpumqhtyd2vm5gsmxrkerugcswt"},{"key":"amount","value":"199997577320474753477adym"},{"key":"receiver","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"amount","value":"199997577320474753477adym"},{"key":"spender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"coinbase","attributes":[{"key":"minter","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"amount","value":"199997577320474753477adym"}]},{"type":"ethereum_tx","attributes":[{"key":"amount","value":"199997577320474753477"},{"key":"ethereumTxHash","value":"0x65fae2e60e95d53d6c7fe7ca7dfa24303503a11457dd68ff6b99336a154d2d13"},{"key":"txIndex","value":"89"},{"key":"txGasUsed","value":"21000"},{"key":"txHash","value":"6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8"},{"key":"recipient","value":"0x5d17690240F30680F360bAc8d53374443661Db23"}]},{"type":"message","attributes":[{"key":"action","value":"/ethermint.evm.v1.MsgEthereumTx"},{"key":"sender","value":"dym1vqu8rska6swzdmnhf90zuv0xmelej4lql0fj3x"},{"key":"sender","value":"dym1edvurn7ugxvlrx3qjy2us7n4tyj3pmgwum7ahw"},{"key":"module","value":"evm"},{"key":"sender","value":"0xCB59c1cfdc4199F19A209115c87A75592510Ed0E"},{"key":"txType","value":"0"}]},{"type":"transfer","attributes":[{"key":"recipient","v..."
"logs":[1 item
0:{3 items
"msg_index":int0
"log":string""
"events":8 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
}
]
"info":string""
"gas_wanted":string"21000"
"gas_used":string"21000"
"tx":{4 items
"@type":string"/cosmos.tx.v1beta1.Tx"
"body":{5 items
"messages":[1 item
0:{...}5 items
]
"memo":string""
"timeout_height":string"0"
"extension_options":[1 item
0:{...}1 item
]
"non_critical_extension_options":[]0 items
}
"auth_info":{3 items
"signer_infos":[]0 items
"fee":{4 items
"amount":[...]1 item
"gas_limit":string"21000"
"payer":string""
"granter":string""
}
"tip":NULL
}
"signatures":[]0 items
}
"timestamp":string"2024-02-06T13:58:55Z"
"events":22 items
[0 - 2]
[2 - 4]
[4 - 6]
[6 - 8]
[8 - 10]
[10 - 12]
[12 - 14]
[14 - 16]
[16 - 18]
[18 - 20]
[20 - 22]
}
}
```

### Notes

When we use RPC, we don't send it to our address but send it to someone else's address...
you can check the error there
https://dym.fyi/tx/6CB6E397EB105A0239B02D12C55B85E2668047A1940BA67EA21FBB98928604A8

**Comment by Wawanahayy** [comment]
please replay team

**Comment by artemijspavlovs** [comment]
closing, this is not related to roller.

issues related to rewards, transactions etc. were processed over discord
