### ISSUE TITLE
Could not find my token in wallet which I transferred from another wallet

### ISSUE THREAD

**Issue by mjihadulislam96** [dymensionxyz/roller#734]
**I have got 55+ DYM & I have transferred it to my Another Wallet but now I can't see them in that wallet.**

Video proof of my transfer
https://drive.google.com/file/d/1yUZFGgm6kW0UaYXoQJfYbicxhZWAgLPQ/view?usp=drivesdk

At first it showed in my another wallet but before the TGE I couldn't find my DYM in the wallet Nor I could find any TX history in explorer🥺. 

As per my assumption it happened because of Blockchain & RPC issue.

This was my airdrop received wallet: 0xD0798d8AcdB95A3f980A39bf908F5Ebc015304Bd

& I have sent to this address: 0x96f6f6970296e65d06327df34714f93f457aa464

This is the Tx hash of that transaction which I can't find history of in DYM explorer (tx hash): 0x4d84dcf6d8974ee7d7006fe1eac32e91b510c8925fce4e44628977b1c4a14fe7

Now I can't find my balance on the address 😬😓: 0x96f6f6970296e65d06327df34714f93f457aa464

Is it means I have lost my airdrop of 300$ worth 😶😬. 

Would love to have support of Team. 

I did try all the ways to check the balance through Kepler & leap wallet but couldn't find.

**Please look at the screenshot below and help me out** 😭

![Screenshot_2024-02-08-10-38-20-55_6822755ba3b6ec553bccdd7479edea06](https://github.com/dymensionxyz/roller/assets/53667291/d4b61689-da64-4c7c-bd92-07bac01657e4)
![Screenshot_2024-02-08-10-38-26-38_6822755ba3b6ec553bccdd7479edea06](https://github.com/dymensionxyz/roller/assets/53667291/66267d1b-1a33-4565-aeb8-34a12eac9505)
![Screenshot_2024-02-08-10-38-34-34_6822755ba3b6ec553bccdd7479edea06](https://github.com/dymensionxyz/roller/assets/53667291/617c2528-f01d-4073-a3b5-b328120ea67e)

Now I found out what happened.

5d ago my transfer showed confirmed but it didn't due to Blockchain issue.

Now I'm seeing in Explorer that 1d ago hacker has taken away my DYM from Airdrop wallet which I thought I have successfully transferred to another wallet 💔💔.

It wasn't my fault but the Dymension Blockchains fault.

I knew that things like this would happen that's why I transferred it to other wallet & showed that I have successfully transferred even token from wallet has gone but now I see it was illusion made by the weaknesses of dymension EVM Chain.

**Comment by santosdios** [comment]
this is really strange, could you provide more information on Discord please? better to close this issue and continue there.
