### ISSUE TITLE
tia claim

### ISSUE THREAD

**Issue by lucasnpost** [dymensionxyz/roller#738]
First of all, thank you very much for the airdrop, it helps a lot to continue betting on serious projects like yours. On the other hand, my question is where I can see my case regarding the TIA claim, since I had an amount in mind and it never arrived. Yes, the Osmo and Atom thing came but the TIA thing didn't and I never understood why. thank you so much.

mi wallet is celestia1k9kep99uc2pxnrt9rjdpm3xrytys9q7mmxc3gd

I have my TIAs for quite some time.

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
