### ISSUE TITLE
CELESTIA STAKER THAT HAS CLAIMED BUT CANT FIND TOKENS

### ISSUE THREAD

**Issue by brainacs** [dymensionxyz/roller#739]
i claimed with this address celestia12nuqgc89k2vwjg68wkqqnh99u8k84zjt9hl4mp as a $TIA staker but cant seem to find any balance

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
