### ISSUE TITLE
I Cant conect my Metamask wallet on the portal web

### ISSUE THREAD

**Issue by HumbertoPuche** [dymensionxyz/roller#741]
### Roller version

DYM portal web 

### OS

Windows 

### Processor Architecture

Web site cant not conect with Metamask

### Others

https://portal.dymension.xyz/dymension/staking

### Steps to reproduce it

![image](https://github.com/dymensionxyz/roller/assets/159593324/df0c7d63-06d7-4d4c-9d48-b0101e35814e)

### Expected result

I want to easy conect to metamask into https://portal.dymension.xyz/dymension/staking so i can buy DYM and stake them

### Actual result

I cant not conect and i cant no see my DYM TOKENS

### Relevant log output

```Shell
It has some problem with the RPC client
```

### Notes

I dont knoe what to do to conect my metamsk red Dym

**Comment by santosdios** [comment]
Sometimes the RPCs are saturated, you can try dym.json-rpc.cumulo.com.en
