### ISSUE TITLE
i did not recive my drop

### ISSUE THREAD

**Issue by tiktakonelive** [dymensionxyz/roller#743]
hi, i claimed my drop for staking Osmo and Atom, but i did not recive anything, could u help me please?

**Comment by Matt2118** [comment]
Good morning, I received confirmation of the Genesis Rolldrop via Drip.Haus on 04 January for 115.27 DYM, however never received the airdrop.
The claim wallet was on Phantom, address: 0x8a2682E608Df762c21DEcEdA636749DA4d6fBD5e
I would be very grateful if you can deal with this for me so I may be part of your growing community.
Please see attached screenshot.
Best regards

![SOL 1 DYMENSION AIRDROP TO PHANTOM 1 04 JANUARY 2024](https://github.com/dymensionxyz/roller/assets/75394292/1fb68316-deb7-4d69-ab7e-b04381de099a)

**Comment by santosdios** [comment]
sorry, airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
