### ISSUE TITLE
Important Bugs with auto sending $DYM when mainnet goes live !

### ISSUE THREAD

**Issue by anakgembala** [dymensionxyz/roller#745]
### Roller version

v1

### OS

windows

### Processor Architecture

AUTO SENDING DYM AT MAINNET

### Others

Hello sir i got issued with my $DYM coin , Im a tester of Dymension was eligible with 300 $DYM , before mainnet comes my dym still 300 coin and after mainnet is live my Dym is auto sending  I dunno why it can happen I cant track other address at dym.fyi explorer so I got confused because I have question in my mind.
1. If new RPC I believe its cant be compromised 
2.Its have eror with RPC at mainnet launch 

I wanna show my pict of screen my explorer my address 
![Issue case](https://github.com/dymensionxyz/roller/assets/131879006/7d8d2d41-79c7-469a-a07e-5d582359f2f9)

### Steps to reproduce it

Check all with block heigh sending at 73 than check it the rpc after and before mainnet or who have stole my 300 DYM.
after this is true because eror with RPC before mainnet please give back the DYM has auto sending at block 73.

![Issue case](https://github.com/dymensionxyz/roller/assets/131879006/c69ad6cb-3080-4523-90ff-9edfd2b12daa)

### Expected result

My biggest hope is my DYM can comeback to my wallet because before mainnet with true live I never connect with any Dapps or doing transaction because I always stay at discord before mainnet launching.

after this is true because eror with RPC just give back the stolen/auto sending coin at mainnet launch in block heigh 73 get back in New wallet address to avoid compromised or hacker.
![Issue case](https://github.com/dymensionxyz/roller/assets/131879006/34290c7f-ce5b-40e8-8cd4-3f1b09a5d056)

Thankyou

### Actual result

Please help me to done with this issued and I want to my 300 $DYM back in my wallet 
![Issue case](https://github.com/dymensionxyz/roller/assets/131879006/2041fba4-90f8-4971-82df-890ab07f949e)

### Notes

Please help me to done with this issued and I want to my 300 $DYM back in my wallet 
![Issue case](https://github.com/dymensionxyz/roller/assets/131879006/8fb0b56d-1960-4252-845e-d68d830a8a66)

**Comment by santosdios** [comment]
as you say that amount of DYM has never reached your mainnet wallet, it is not relevant that you had it previously on testnet, ... please contact Discord to help you in a more agile way. We are closing this issue
