### ISSUE TITLE
Dymension mainnet auto sending 300 token when mainnet start !

### ISSUE THREAD

**Issue by dimasbenjoz** [dymensionxyz/roller#746]
Hello sir please help for I have issued with my dymension coin , I lost my 300 worth of $DYM at mainnet because weird activity while mainnet goes live , I dont know why these can happen with my own wallet , I know that Dymension have new RPC in my opinions it cant be compromised or drain , and my biggest thinks is that my wallet got eror RPC / RPC bugs after mainnet 100% live , I swear I never do send or any transaction before RPC at 100% mainnet and I still have my 300 $DYM before mainnet live I lost at 71 block heigh. please sir check this issued and I want my DYM comeback to my wallet ! 

Note : I hope this is never got compromised or draining and the issue is fix I hope I want to get back my 300 DYM and I will replace with new wallet to avoiding draining or compromised at my first wallet ! 
here I wanna show my screenshot pict in my explorer scan at dym.fyi explorer 
![dym issue](https://github.com/dymensionxyz/roller/assets/119735159/46d8ce12-9a27-4a3e-9694-30a642d7ce92)

My Dymension metamask wallet : 0x2619081bdE1Abd6F67aA2B330F8FBAeF6554C817
My Dymension Keplr wallet : dym1ycvssx77r27k7ea29veslra6aaj4fjqhdz69j4

Thankyou Devs and Teams by Dymension

**Comment by santosdios** [comment]
From what you say I think your wallet has been compromised, so it is not possible to do anything
