### ISSUE TITLE
DYM Rolldrop confirmed but not received

### ISSUE THREAD

**Issue by Matt2118** [dymensionxyz/roller#751]
Good morning, I received confirmation of the Genesis Rolldrop via Drip.Haus on 04 January for 115.27 DYM, however never received the airdrop.
The claim wallet was on Phantom, address: 0x8a2682E608Df762c21DEcEdA636749DA4d6fBD5e
I would be very grateful if you can deal with this for me so I may be part of your growing community.
Please see attached screenshot.
Best regards
M

![SOL 1 DYMENSION AIRDROP TO PHANTOM 1 04 JANUARY 2024](https://github.com/dymensionxyz/roller/assets/75394292/2dbb6120-a59a-441e-a307-db93a760217d)

**Comment by santosdios** [comment]
hey you have a balance in that wallet, I believe you have received the tokens, please continue on Discord for more information.

https://dym.fyi/address/0x8a2682e608df762c21deceda636749da4d6fbd5e
