### ISSUE TITLE
can't claim dym on my EVM etherum on my phantom wallet

### ISSUE THREAD

**Issue by Superconcept** [dymensionxyz/roller#752]
### Roller version

roller version

### OS

etc

### Processor Architecture

Superconcept

### Steps to reproduce it

0xEf15FE560730BeC1f7Fe6872cC59bb3bc93522d0

this is my EVM address which I bound my DYM. I can't claim them on phantom wallet and I don't know how to claim in on my MM or Keplr wallet to stake my DYM.
my dym adress on MM is arlready there
0x0E1B494c1B9602DE9F02464Df96f08eCE3B39372

### Expected result

I want my DYM pls.

### Actual result

to get it on my wallet

### Notes

thx a lot

**Comment by santosdios** [comment]
Success in getting DYM from Phantom to Metamask  start by getting DYM chain on Metamask at https://chainlist.org/chain/1100 then go to Phantom Wallet and copy private key for the ethereum chain then go to Metamask and click on add account then import wallet and paste private key. You will now see your DYM in Metamask on the DYM chain..
Please continue on the Discord support channel for better tracking.
