### ISSUE TITLE
Roller doesnt function properly out the box

### ISSUE THREAD

**Issue by resided** [dymensionxyz/roller#758]
### Roller version

roller

### OS

Linux 

### Processor Architecture

5.15.0-94-generic

### Steps to reproduce it

Install Roller on a brand new updated Linux machine, the sequencer will always stop after around 2 minutes and cannot continue resulting in an unhealthy machine.

### Expected result

Redesign Roller 

### Actual result

Sequencer failed to start

**Comment by omritoptix** [comment]
can you attach relevant logs?
