### ISSUE TITLE
Dym token not got in my metamask 

### ISSUE THREAD

**Issue by garudraj** [dymensionxyz/roller#760]
Respected sir 
I got dym Airdrop in my solana address and i was claimed on metamask address but token was not got please help me about this i am attaching some proof about this please check My address transection 
![IMG_20240109_213857_959](https://github.com/dymensionxyz/roller/assets/79732331/9e069d03-947b-4ff4-9233-70fd29424fbd)

My solana address: EP2yarLaBcFAB4KWQ93WBMcrSadwLUtFBm6D5y7uxULA

My metamask: 0xA2a735fbdbF62A08e49deaBf21e49a0E92d2b832

**Comment by santosdios** [comment]
sorry but airdrop is already distributed and it seems that the process does not show any errors so the team considers this issue closed as there is no evidence of an error in the process. For more information please continue on Discord
