### ISSUE TITLE
[Feature Request]: Add better tracking for eligibility when it comes to airdrop and CLAIM SHOULD BE AUTOMATIC. 

### ISSUE THREAD

**Issue by 0xDevNor** [dymensionxyz/roller#761]
### Implementation ideas

I was using your airdrop page to check for eligibility and i was eligible but now when the day came to claim my adress is displaying 0 DYM and the page to check if your eligible has been removed. Maybe you could keep this up for next time or help out to solve the issue.

**Comment by santosdios** [comment]
sorry but the airdrop is already distributed and it seems that the process does not show any bugs so the team considers this topic closed as there is no evidence of an error in the process, Could you please close this thread and continue on Discord?
