### ISSUE TITLE
i am trying to Unstake from "Coinage x DAIC" validator .. but i keep getting a "Can't fetch data from Dymension client, please try again later" error .. please help!!

### ISSUE THREAD

**Issue by dennis-smit** [dymensionxyz/roller#765]
### Roller version

roller version

### OS

/

### Processor Architecture

uname

### Others

i am trying to Unstake from "Coinage x DAIC" validator .. but i keep getting a "Can't fetch data from Dymension client, please try again later" error .. please help!!

### Steps to reproduce it

unstake -> and get error

### Expected result

unstaking of my funds

### Actual result

error -"Can't fetch data from Dymension client, please try again later"

**Comment by santosdios** [comment]
We are already supporting you on Discord, please continue there.
