### ISSUE TITLE
[Feature Request]: Staking DYM

### ISSUE THREAD

**Issue by DaiThinh92** [dymensionxyz/roller#768]
### Implementation ideas

Hello Dev Team,
I have a question about staking.

Once day ago, I staking DYM on portal,
I went to check and discovered that the amount of DYM that was staking was no longer in Staked but was unstaked. I checked the wallet address and it said "their from validator".

By no longer being in the stake section, I no longer have a chance to receive the airdrop. So I asked Team Dev support to help me.
Thks
![image](https://github.com/dymensionxyz/roller/assets/146215945/1d13cebc-8d1e-40ac-8760-f771bbbb3a90)

**Comment by santosdios** [comment]
it's not the team's responsibility the features of third party airdrops, but in any case you should check why those actions were performed on your wallet, if it wasn't you the wallet could be compromised....
I close the issue, for more information please access the Discord.
