### ISSUE TITLE
Unable to redelegate

### ISSUE THREAD

**Issue by Etherforever88** [dymensionxyz/roller#771]
### Roller version

https://portal.dymension.xyz/dymension/staking

### OS

https://portal.dymension.xyz/dymension/staking

### Processor Architecture

https://portal.dymension.xyz/dymension/staking

### Steps to reproduce it

Restake my DYM with others validators. 

### Expected result

Able to restake DYM with other Validators

### Actual result

![image](https://github.com/dymensionxyz/roller/assets/137176429/c90b23b9-4e97-46ea-8d11-6feb67542bf4)

No valid option to restake DYM with other Validators

**Comment by Raoulduke881** [comment]
Having the very same issue on portal.dymension.xyz with MetaMask, no problems with wallets such as Keplr.

**Comment by santosdios** [comment]
it is a bug known by the team that they are trying to fix, we will keep you informed on Discord, we proceed to close the issue
