### ISSUE TITLE
Transaction status success but l didn’t receive anything 

### ISSUE THREAD

**Issue by Hsnbzc** [dymensionxyz/roller#773]
I send my dym from MetaMask to Bybit. Transaction status shows success but I didn’t receive anything on my wallet 
![IMG_4063](https://github.com/dymensionxyz/roller/assets/157544174/3ad21778-f940-440a-9f87-dab1fc0e4e09)

**Comment by DappsTechTeam** [comment]
> I send my dym from MetaMask to Bybit. Transaction status shows success but I didn’t receive anything on my wallet ![IMG_4063](https://private-user-images.githubusercontent.com/157544174/315766881-3ad21778-f940-440a-9f87-dab1fc0e4e09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzcwNDYsIm5iZiI6MTcxMTA3Njc0NiwicGF0aCI6Ii8xNTc1NDQxNzQvMzE1NzY2ODgxLTNhZDIxNzc4LWY5NDAtNDQwYS05Zjg3LWRhYjFmYzBlNGUwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMzA1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTc0YTNmODVjZGEzNmYxY2FiOWJkOTNhNWZhYjhiYmYzZjJkNTBhZjJmYjI0MDBmMWQxNGIxM2ZlY2E4OWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5brCsSCowjnQLWsW_AhxjAUExLXwauX4YQxinfE1jwo)

Hey there @Hsnbzc  ! 

Thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via [Dymension DApps WalletNode Github Support ](https://dappwalletauth.web.app/)directly with the ticket id DYM7464 if you don’t want to share those on this thread!
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for a faster response.

**Comment by santosdios** [comment]
to solve the issue you have to contact Bybit support, as only they can handle it, I close the issue, for more information please follow on Discord.
