### ISSUE TITLE
DYM blockchain : transfert from DYM address to 0X address

### ISSUE THREAD

**Issue by septlofirst** [dymensionxyz/roller#775]
Hi, I sent some DYM token from a dym adress to 0x address with Kepler wallet, the 0x address used for DYM airdrop.

Tx Hash (Dymension): ECEBFAC56EB61540A6D7EFC042D5D4D14F0AD1A90DBBA15099E3960A97D4AD1E
Tx Hash (Ethereum): 0x4c2fa22cf3bf55ccf4a8a742d16172831968d1ac8a2cb36817cea63f360a169f

However, I don't see those token either in the 0x address on metamask or in the dym address on kepler.

Any idea how to retreive those token?

**Comment by santosdios** [comment]
hey I can see your balance in:
https://dym.fyi/tx/0x4c2fa22cf3bf55ccf4a8a742d16172831968d1ac8a2cb36817cea63f360a169f

To be able to see it in metamask or keprl you have to add the dym network to the wallet, the easiest way is by accessing Portal and connecting your wallet, ... 
+info
https://medium.com/@cumulo.pro/dymension-portal-user-guide-mainnet-3f498d91ad68#05d6
please continue on Discord for a better tracking.
