### ISSUE TITLE
roller tx register command should support permissioned accounts

### ISSUE THREAD

**Issue by artemijspavlovs** [dymensionxyz/roller#777]
### Roller version

v1.0.1-beta-18-g2a0455b

### OS

Ubuntu 22.04.3 LTS

### Processor Architecture

aarch64

### Steps to reproduce it

after initializing the rollapp run

```sh
roller tx register
```

### Expected result

rollapp and sequencer is registered onto the hub

### Actual result

registration fails

### Notes

`roller tx register` command tries to use the same account for both, rollapp and the sequencer. Instead, there should be a way to provide a whitelisted account to register the rollapp and the account to use for registering the sequencer.

**Comment by omritoptix** [comment]
gonna close it as it wont be relevant in permissionless.
