### ISSUE TITLE
CONNECTION FAILED ERROR

### ISSUE THREAD

**Issue by oekxbt** [dymensionxyz/roller#778]
### Roller version

I have no idea what is this

### OS

s

### Processor Architecture

s

### Others

I've been facing with this error code. It been two days passed that the 21 days are done.
What is this error code?
![Ekran görüntüsü 2024-03-30 193510](https://github.com/dymensionxyz/roller/assets/165499889/4d6e4501-8a60-4966-a87a-1ce3a3ce520c)

### Steps to reproduce it

h

### Expected result

h

### Actual result

h

### Relevant log output

```Shell
h
```

### Notes

h

**Comment by santosdios** [comment]
This is an issue that can have several reasons, including low bandwidth, network or RPC saturation, the best solution is to clear the browser cache and refresh the page. Please continue with further updates on Discord, we will proceed to close the issue.
