### ISSUE TITLE
Cant start sequencer 

### ISSUE THREAD

**Issue by yishay-dym** [dymensionxyz/roller#81]
New terminal, rollapp is registered on the hub and previously configured. 

cmd: roller sequencer start:

![Screen Shot 2023-06-20 at 12 14 35](https://github.com/dymensionxyz/roller/assets/109034310/510a3bbc-ad43-4c0c-a6cc-2bbe4de35394)

**Comment by ItayLevyOfficial** [comment]
Happened with old version. Didn't happen all the time. Need to try and reproduce with new version.

**Comment by mtsitrin** [comment]
it happens when switching from older version to newer version without deleting the `app.toml`
