### ISSUE TITLE
Change domain of roller install to a branded one

### ISSUE THREAD

**Issue by yishay-dym** [dymensionxyz/roller#82]
Currently the cmd to install roller is:
`curl -L https://github.com/dymensionxyz/roller/releases/download/v0.0.0/install.sh | bash`

I believe this install cmd will be marketed in various places, hence a branded domain is necessary:

 I propose the following domain:
 roller.dymension.xyz/install 
 
 which will be marketed:
 
 `curl -L https://roller.dymension.xyz/install | bash`

**Comment by omritoptix** [comment]
Should be done after the deployment of this to our servers #235
