### ISSUE TITLE
Improve error message if sequencer already registered

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/roller#946]
Currently we get
        
      `  * Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: not the initial sequencer: unmet precondition [dymensionxyz/dymension/v3/x/sequencer/types/errors.go:30] With gas wanted: '18446744073709551615' and gas used: '185452' : unknown request`

Roller should catch the err and print a prettified message.

**Comment by artemijspavlovs** [comment]
![Image](https://github.com/user-attachments/assets/04d431df-4778-428d-8777-f9ed67f0d5d3)
