### ISSUE TITLE
Roller creates new sequencer on Hub even though rollapp already has a sequencer registered

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/roller#998]
### Roller version

~ roller version 💈 Roller version 1.7.0-alpha-rc01 💈 Build time: 2024-09-18T10:18:18Z 💈 Git commit: 1be4b7c6efc575260796f22e475c9431bd4affde

### OS

mac 14.4

### Processor Architecture

arm64

### Steps to reproduce it

Create a rollapp
Use roller to register sequencer
Delete roller
do roller rollapp init

### Expected result

Should use existing registered sequencer

### Actual result

It will create and ask to fund new sequencer addr

**Comment by artemijspavlovs** [comment]
The issue references removal of the `.roller` 

then creation of a new sequencer is expected as roller has all the information about the sequencer instance. and there can be more then one sequencer for a rollapp.

'moving' a sequencer to a different host is not currently a feature of roller.
